### ISSUE TITLE
[Feature] Hidden Folders

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#1]
Hidden Folders should not be shown or at least a bit transparent
If possible read from windows option if they are shown, if yes show transparent

**Comment by topeterk** [comment]
Current state: Windows Explorer settings are used to actually hide/show entries in STM.

If they shall be shown transparent this must be implemented otherwise this issue can be closed.
@Hofknecht, please check what the intention of STM is.

**Comment by Hofknecht** [comment]
Had a look on the code and tested, it is working. Great job!

Created extra task for transparent:
https://github.com/Hofknecht/SystemTrayMenu/issues/31
