### ISSUE TITLE
[Feature] Code review tool

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#10]
We need a code review tool to improve the code style.
Goal should be perfect readable code.

**Comment by Hofknecht** [comment]
https://de.wikipedia.org/wiki/Lint_(Programmierwerkzeug)
check this tool

**Comment by topeterk** [comment]
in case of alternatives, maybe one of these?
[https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#.NET](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#.NET)

**Comment by Hofknecht** [comment]
linked in [Archieve] #50

**Comment by Hofknecht** [comment]
linked in [Archieve] #50

**Comment by Hofknecht** [comment]
Doing Microsoft.CodeAnalysis.FxCopAnalyzers with 
[Feature] CodeBeauty&Refactor #49

**Comment by Hofknecht** [comment]
we are using fixcop now

**TODO**: 
-create commit rules

> -Run FixCop
-Increase Version in Assembly file
-Commit Message like #xx, #xx, version x.x.x.x
-Update Issue and set it to close
-When not complete, use a branch (to do implement the process)

-check for more (expecially gdi memory leaks analyzer & code stlye analyzer)

**Comment by Hofknecht** [comment]
[Feature] Code Analyze and Refactor 0.11 #88  is the follow up issue to look for more anayzers
closing this
