### ISSUE TITLE
[Feature] Mark text from search

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#100]
Mark text from search

![image](https://user-images.githubusercontent.com/52528841/83969016-7bfa8880-a8cd-11ea-83ad-cd5b0941b537.png)

e.g. when searching 'mar'
**Mar**kus
S**mar**t Home

**Comment by Tanjalibertatis** [comment]
We could mark the search result by underlining insted of printing in bold, like here:
![underline search result](https://user-images.githubusercontent.com/62262740/84036542-9ef46d80-a99d-11ea-9a55-adef42bbaef2.png)

**Comment by Hofknecht** [comment]
not possible with datagridviewrow.
If we need own control there we will come back to this topic
