### ISSUE TITLE
[BUG] displays the error message "Couldn't register the hotkey" at launch

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#102]
Problem from #55,#56 (detected in #101 )

 "Couldn't register the hotkey"  is thrown means hotkey is already used
=> reproduce this, app should not fail in case default hotkey is set, consider using better default hotkey

**Comment by Hofknecht** [comment]
app crashes is probably not true, the user just not know, that he needs to klick into systemtraymenu

**Comment by Hofknecht** [comment]
Consider if it would help to put a active taskbar item and to open stm by this
![image](https://user-images.githubusercontent.com/52528841/85223781-ca2b8380-b3c5-11ea-9224-22a23081bd90.png)

**Comment by topeterk** [comment]
Is registering the hotkey failing because of the window handle?
It is possible to register a hotkey for the calling thread, maybe this would be a better approach?

**Comment by Tanjalibertatis** [comment]
As default hotkey we could use 'Alt Gr' + 'Apps'.

**Comment by Tanjalibertatis** [comment]
When setting 'Page down' as hotkey, the app crashes.

**Comment by Hofknecht** [comment]
created extra task for taskbaritem
[Feature] Show icon in taskbar when application is running #115
