### ISSUE TITLE
[Feature] Filter to hide files/folders

### ISSUE THREAD

**Issue by topeterk** [Hofknecht/SystemTrayMenu#11]
**Is your feature request related to a problem? Please describe.**
When working on certain projects one maybe would like to hide some folders or files.

**Describe the solution you'd like**
Option to filter entries to hide them from the list.

**Describe alternatives you've considered**
(Maybe additionally for later) support of .gitignore or similar as a default filter list that can be activated.

**Additional context**
---

**Comment by Hofknecht** [comment]
linked in [Archieve]

**Comment by Hofknecht** [comment]
linked in [Archieve] #50

**Comment by Hofknecht** [comment]
putted the idea to archive because .gitignore idea
but user can set to hide so should be solved
