### ISSUE TITLE
[BUG] ConfigurationErrorsException: Failed to save settings

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#120]
From Window Store SystemTrayMenu Bug reported 1.0.10.0

System.Configuration.ConfigurationErrorsException: Failed to save settings: Unable to save config to file 'C:\Users\user\AppData\Local\TAMAHO\SystemTrayMenu_Url_smo4m4351v3slu5x443vqepd0wrasblp\1.0.10.0\user.config'. ---> System.Configuration.ConfigurationErrorsException: Unable to save config to file 'C:\Users\user\AppData\Local\TAMAHO\SystemTrayMenu_Url_smo4m4351v3slu5x443vqepd0wrasblp\1.0.10.0\user.config'. at System.Configuration.Internal.WriteFileContext.ReplaceFile(String source, String target) at System.Configuration.Internal.WriteFileContext.Complete(String filename, Boolean success) at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext, Boolean assertPermissions) at System.Configuration.Internal.DelegatingConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext, Boolean assertPermissions) at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.WriteCompleted(String streamName, Boolean success, Object writeContext) at System.Configuration.UpdateConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext) at System.Configuration.Internal.DelegatingConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext) at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll) at System.Configuration.Configuration.SaveAsImpl(String filename, ConfigurationSaveMode saveMode, Boolean forceSaveAll) at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings) --- End of inner exception stack trace --- at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings) at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values) at System.Configuration.SettingsBase.SaveCore() at System.Configuration.SettingsBase.Save() at System.Configuration.ApplicationSettingsBase.Save() at SystemTrayMenu.Config.UpgradeIfNotUpgraded() at SystemTrayMenu.Program.Main()

**Comment by Hofknecht** [comment]
thank you community for reporting this bug
also reported by  A.W. , D.T. D.H. 

=> 4 times reported

will upgrade the prio

**Comment by topeterk** [comment]
Any ideas what could cause this?
A file in the home directory should always work unless a system miss-configuration, absence of the storage drive, timeout on writing it (network shared or some sort of online mapped drive) or an error during writing of files in general (full HDD).
Or conflict due to already opened file that is still in use by another instance of this application?

**Comment by Hofknecht** [comment]
i think other instance should not be possible

i assume missing rights, so i tried to store at same location where logfile was successfully stored

some info's here
https://stackoverflow.com/questions/982354/where-are-the-properties-settings-default-stored#:~:text=If%20you%20store%20settings%20for,public%5Cappdata%5Clocal%20).


we used solution from here
https://stackoverflow.com/questions/2265271/custom-path-of-the-user-config/11398536#11398536
