### ISSUE TITLE
[Feature] portable 3mb vs windows store 143 mb

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#121]
Are there any ways to reduce the windows store package (60mb, msxibundle). Is it depending from the screenshots added to the package? Are the screenshots necessary or is windows accepting the package also without screenshot in the package ?

e.g. greenshot the app is also 4,64 mb so this is definitly a issue

=> screenshots of package ~2mb, not the issue

**Comment by Hofknecht** [comment]
maybe easier to write mail to support
Microsoft Store Report App <reportapp@microsoft.com>

and ask for these things


---
Before make some research ask google

**Comment by Hofknecht** [comment]
e.g. greenshot the app is also 4,64 mb so this is definitly a issue

**Comment by Tanjalibertatis** [comment]
C:\Program Files\WindowsApps\49543SystemTrayMenu.SystemTrayMenu_1.0.11.0_x86__y4xj13v8chxp8\SystemTrayMenu

![2020-07-28 12_58_35-Issues · Hofknecht_SystemTrayMenu](https://user-images.githubusercontent.com/62262740/88657401-245cea00-d0d2-11ea-80d9-989dd26b586c.png)

**Comment by Hofknecht** [comment]
Probably the only way would be to remove using of these dll's ?
also related to  #91 COMReferences in .NET Core 3.1

**Comment by topeterk** [comment]
Those files should come with the .Net framework and should not bundled with that application at all, right?
This way the application would not use the system DLLs (that are most likely newer than the ones from STM package) which is a also a potential security risk.

**Comment by Hofknecht** [comment]
won't fix for now, we put it to FAQ
