### ISSUE TITLE
[Feature] Option to remove taskbar icon

### ISSUE THREAD

**Issue by Mordecai00** [Hofknecht/SystemTrayMenu#123]
Have downloaded this program for use in the system tray but the taskbar icon is persistent. Not sure if this is by design.

**Comment by Hofknecht** [comment]
Thank you for feedback

Yes, is by design, we added with issue [Feature] Show icon in taskbar when application is running #115
but i already considered to make it as option

TODO: Add option to remove tasskbar item

**Comment by Hofknecht** [comment]
![2020-08-06 10_55_09-](https://user-images.githubusercontent.com/52528841/89512299-51488580-d7d3-11ea-8c56-1fdc8be8560a.png)

done 

thank you @Mordecai00 for the idea

**Comment by Mordecai00** [comment]
no problem - when is it going in? i downloaded again and can't see the
expert section in settings.

**Comment by Hofknecht** [comment]
Hello @Mordecai00 

thank you. yes we not yet released.

now released with a couple of other new features in SystemTrayMenu version 1.0.15.0
