### ISSUE TITLE
[Feature] Option to only single click instead double click

### ISSUE THREAD

**Issue by Holgermh** [Hofknecht/SystemTrayMenu#125]
Would it be possible to make Double/Single Click an Option? I prefer Single Click.
Thanks for this fine program.

**Comment by Hofknecht** [comment]
related to #66   "not good for touch, then when you click wrong item it will be directly executed"
=> now items also bigger, so this happens not that often, addioanlly we could exclude for touch or make extra option for touch
=> For #66 as option ok

related to #82 => Double click, should only execute once
=> For #82 as option ok

related to #18 => Leave contextmenu with click
=> For #18 as option ok

=> Rdy for planning

**Comment by topeterk** [comment]
@Hofknecht There is also a Windows options for the Explorer to use single or double clicks.
Maybe use that option as a default setting unless the user specifically selects either of those for the STM?

![image](https://user-images.githubusercontent.com/4932525/88666696-b66bef00-d0e0-11ea-9e19-c6f82b0d62b3.png)
Sorry for the German image. I'm talking about the second group box of the menu at "Windows Explorer" > "Options" > "Change search and file options" (or anything similar)

**Comment by Hofknecht** [comment]
![2020-08-06 10_51_40-SystemTrayMenu (Running) - Microsoft Visual Studio](https://user-images.githubusercontent.com/52528841/89511956-d7180100-d7d2-11ea-8775-e33de68ca6d3.png)

Thank you @topeterk for the idea. We used texts of it
