### ISSUE TITLE
[BUG] Fix click on menu sometimes stops loading

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#126]
Fix click on menu sometimes stops loading but should only start loading

**Comment by topeterk** [comment]
Is there a more detailed description about this issue?
I don't get it, what problem here actually is.

**Comment by Hofknecht** [comment]
Usually when you move the mouse over a folder it takes 200 ms then it starts loading the submenu. 
With click you can directly start loading it.

The issue occures when you already waited 200ms, but it takes longer to load the menu (e.g. network folder) and then you click once on it, then loading for submenu stops

but i expect nobody uses it like this so i will downgrade the prio

**Comment by Hofknecht** [comment]
removed the stop when single click. single click now working like expected, it jumps over the 200 ms and starts directly the load
