### ISSUE TITLE
[BUG] Fix InteropServices.COMException 0x8007000F

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#128]
System.Runtime.InteropServices.COMException (0x8007000F): The system cannot find the drive specified. (0x8007000F)   at Shell32.IShellLinkDual2.get_Target()   at SystemTrayMenu.Utilities.FileLnk.GetShortcutFileNamePath(Object shortcutFilename)   at SystemTrayMenu.Utilities.FileLnk.GetResolvedFileName(String shortcutFilename)   at SystemTrayMenu.DataClasses.RowData.SetLnk(Boolean

Issue occurs when I choose the desktop as the root folder, the program then goes into a perpetual loop of, click ok to send an email or click no, if you click no, it closes and auto reopens and gives the same error notice, I had to run task manager/end program to get out of it.

It works fine choosing a different root dir so its 

------------------

System.Runtime.InteropServices.COMException (0x8007000F): The system cannot find the drive specified. (0x8007000F)   at Shell32.IShellLinkDual2.get_Target()   at SystemTrayMenu.Utilities.FileLnk.GetShortcutFileNamePath(Object shortcutFilename)   at SystemTrayMenu.Utilities.FileLnk.GetResolvedFileName(String shortcutFilename)   at SystemTrayMenu.DataClasses.RowData.SetLnk(Boolean

Issue occurs when I choose the desktop as the root folder, the program then goes into a perpetual loop of, click ok to send an email or click no, if you click no, it closes and auto reopens and gives the same error notice, I had to run task manager/end program to get out of it.

It works fine choosing a different root dir so its one of 2 things, it does not like a file type, the desktop full stop. I have various items, from exe’s to PDF (should be ok as they are fine using different folder) to program shortcuts to rar files etc, one of those I expect, perhaps an exception to at least ignore exe’s as a starting block.

Please can you email me if and when a fix is ready to try as ive removed it for now as its only yhr desktop I would use it for, if you saw it you would understand lol

Regards

Martin T.

------------

Hi again, apologies for the half an email I sent you, not the one below, the other one..

After reading the actual error code, it looks like its regarding the shortcut I have for a folder on a backup drive, this is quite important so could do with working and not just editing out if possible please? The drive only gets added later on in the day and I use the computer from about 1:30am  without the drive attached...

Yours hopefully

Martin T.

--------------------------------------------------------------

System.Runtime.InteropServices.COMException (0x8007000F): The system cannot find the drive specified. (0x8007000F)   at Shell32.IShellLinkDual2.get_Target()   at SystemTrayMenu.Utilities.FileLnk.GetShortcutFileNamePath(Object shortcutFilename)   at SystemTrayMenu.Utilities.FileLnk.GetResolvedFileName(String shortcutFilename)   at SystemTrayMenu.DataClasses.RowData.SetLnk(Boolean

Issue occurs when I choose the desktop as the root folder, the program then goes into a perpetual loop of, click ok to send an email or click no, if you click no, it closes and auto reopens and gives the same error notice, I had to run task manager/end program to get out of it.

It works fine choosing a different root dir so its one of 2 things, it does not like a file type, the desktop full stop. I have various items, from exe’s to PDF (should be ok as they are fine using different folder) to program shortcuts to rar files etc, one of those I expect, perhaps an exception to at least ignore exe’s as a starting block.

Please can you email me if and when a fix is ready to try as ive removed it for now as its only yhr desktop I would use it for, if you saw it you would understand lol

Regards

Martin T.

**Comment by Hofknecht** [comment]
Verify root cause of bug, maybe this could help
http://www.wiki-errors.com/wiki-errors.php?wiki=0X8007000F#4

todo check if we could catch the exception and only warn in logfile

**Comment by topeterk** [comment]
Just as an idea when solution is found:
Gray out the entry when its shortcut cannot be resolved or mark it as broken link using an icon overlay?

**Comment by Hofknecht** [comment]
probably this line is failing:
ShellLinkObject link = (ShellLinkObject)folderItem.GetLink;

will add a catch COMException

because i could not reproduce hope this will fix the issue

the related file (it is a shortcut *.LNK) will be then visible in logfile as warning
