### ISSUE TITLE
[Feature] Other taskbar orientations 

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#13]
Missing handling of other taskbar orientiations. 
(or at least a hint that this is not supported, but now i think we should support it)

Think about how to solve

**Comment by Hofknecht** [comment]
linked in [Archieve] #50

**Comment by Hofknecht** [comment]
TODO: still a issue

**Comment by Hofknecht** [comment]
vote for this feature request here
https://www.reddit.com/user/Equeslibertatis/comments/gz3uam/systemtraymenu/

![image](https://user-images.githubusercontent.com/52528841/88449691-1cd6e000-ce49-11ea-86e4-9841821b129a.png)

Gigaify:
Feature request: Detect system tray location? As for me I have three monitors, the "Main monitor" is not the one I have my taskbar on, in addition to that, my taskbar is located on the top. Clicking the icon launches the UI in the bottom right assuming I have my taskbar in a "normal" person location lol Would be nice to have it at the top right of the monitor i have my taskbar, for us crazy people with taskbars at the top 😅

**Comment by Hofknecht** [comment]
#136

**Comment by Hofknecht** [comment]
Thank you 
Peter Kirmeier topeterk

**Comment by Ryonez** [comment]
It still opens on the incorrect monitor.
My system tray is on monitor 2, SystemTrayMenu still open on monitor one.

**Comment by Hofknecht** [comment]
@Ryonez 
Thank you for the feedback!
It is because your monitor 2 is the primary screen.

We will implement a option to set the position:
[Feature] Option to set a position of the menu #229

**Comment by Ryonez** [comment]
Yes, I am aware of this, unfortunately I used the wrong monitor number when referring to which monitor it was opening on.
Thank you though, I'll keep an eye on this new issue.
