### ISSUE TITLE
[BUG] Window title bar appears when scaling is changed

### ISSUE THREAD

**Issue by topeterk** [Hofknecht/SystemTrayMenu#137]
In Windows settings change the scaling while STM is open.
A window title bar appears:
![image](https://user-images.githubusercontent.com/4932525/94350541-7331ec00-004f-11eb-9928-ab1fedfe01d5.png)

 - OS: Microsoft Windows 10 Pro 2004
 - Version 1.0.16.1

**Comment by Hofknecht** [comment]
yes, this window is a workaround for
[Feature] Show icon in taskbar when application is running #115

i found no other way to show a taskbaritem, the windows is placed out of the desktop range, but it seems i come into your desktop in you case.

now i think we should remove #115, or at least disable it by default
(i'm also considering to make the one click option enabled by default)

**Comment by Hofknecht** [comment]
when i tried to reproduce it restarts when display settings / scaling changed trough these lines

SystemEvents.DisplaySettingsChanged += AppRestart.ByDisplaySettings;
internal static void ByDisplaySettings(object sender, EventArgs e)
        {
            Restart(GetCurrentMethod());
        }

therefore it does not appear in my environment at the moment

found some articles in google related to "DisplaySettingsChanged not raised"
https://www.pcreview.co.uk/threads/does-not-receive-events-from-microsoft-win32-systemevents-when-running-as-a-service.1710603/ => not raised in a service
https://www.daveoncsharp.com/2009/10/how-to-capture-system-events-using-csharp/ => not raised in Vista

not sure if this helps.

did not found other good solutions instead using DisplaySettingsChanged 

needs further analyses why DisplaySettingsChanged not raised in your case
(maybe upgraded win10 from vista? maybe special start of stm as a service?)

maybe as workaround you can restart stm manually in this cases or disable option #115

**Comment by Hofknecht** [comment]
peter mentioned that also other apps had problems in his case, probably related from win7 to win10 upgrade, but not sure, maybe reinstall win7 could help, but that we will not make at the moment ; )

for the moment we're closing the issue

**Comment by Hofknecht** [comment]
only FYI
right click on app and then set to application here solves to problem (mentioned from peter)
![image](https://user-images.githubusercontent.com/52528841/97087609-9f7b6100-162b-11eb-8ea1-2fb0754dac04.png)

but we are considering to remove the taskbarform (also a other user asked per mail if the whole behavior of taskbarform is wrong)
