### ISSUE TITLE
[Bug, Find Solution] Special characters (e.g. chinese)

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#14]
chinese characters => no icon
If an itemname contains e.g. chinese characters there is an exception.
Check if also the icon is not shown, is the exception handling also ok?, is then the disposing of the menu ok?

Test if there are more problems with special characters

**Comment by topeterk** [comment]
the initial exception fixed: [commit](https://github.com/Hofknecht/SystemTrayMenu/commit/a5aee52858fb0e83aaba8c1310d68fb21d58b907)
needs further investigation why SHGetFileInfo fails
