### ISSUE TITLE
[Feature] Enable WinL as modifier for hotkey and make Ctrl+WinL the new default hotkey

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#153]
Seems Ctrl+WinL seems to be a good new default hotkey
e.g. current one (Alt + Ctrl + Apps) has the disadvantage that the context menu rare times opens (due to pressing Apps key only)

Thank you Blacky for that hint with TrayLauncher
https://www.blackysgate.net/files/upload/TrayLauncher-Homepage 
https://code.google.com/archive/p/traylauncher/wikis/TrayLauncher.wiki 

- [x] Enable WinL as modifier for hotkey and make Ctrl+WinL the new default hotkey
- [x] Check also if there are more features we could use from TrayLauncher

**Comment by jakkaas** [comment]
If i could add, it would be nice if we could add mouse key as a hotkey. I would like to add Ctrl+ mouse left lick as a hotkey

**Comment by blackcrack** [comment]
@jakkaas a hotkey editor could be possible where makes possible for for configuration the hotkeys.. in the Settings-Editor.. but wait, what @Hofknecht add at all and how looks the list .. i guess he make a list at a letter with the whole points by testing out in front of the Computer and and then a to do list what all want include and for edit to check it later ..

### ToDo List
 - [ ] Point 
 - [x] Point 
 - [ ] Point

**Comment by Hofknecht** [comment]
@jakkaas  Thank you, see also follow up
[Feature] Option to appear at mouse location and Hotkey Mouse Click #135

@blackcrack , see also follow up
[Feature] Settings Customize #160
if you have more ideas from traylauncher, please let me know or create a feature/bug
