### ISSUE TITLE
[Feature] Update to .NET 6

### ISSUE THREAD

**Issue by blackcrack** [Hofknecht/SystemTrayMenu#157]
have installed since NVidia Drivers to NetFX4.5 and actual is NetFramework 5.X and Preview with 6.x is on the way..

had think by the question for NetFX of desktop 3.1 
"wth!"

8\)

best
Blacky

**Comment by Hofknecht** [comment]
yes, you are right,

we are at 
https://dotnet.microsoft.com/download/dotnet/3.1

and can upgrade easily to latest version
https://dotnet.microsoft.com/download/dotnet/5.0

do we have any advantages from this?
one disadvantage is that everybody needs to install latest framework version, often the people don't want to

as soon as necessary we will switch

**Comment by blackcrack** [comment]
already installed.. i am more as 20 Years at the net..

**Comment by Hofknecht** [comment]
maybe we can folllow these steps to migrate to .NET 5
https://docs.microsoft.com/de-de/dotnet/desktop/winforms/migration/?view=netdesktop-5.0&preserve-view=true

analyzer says 100% compatible
https://docs.microsoft.com/de-de/dotnet/standard/analyzers/portability-analyzer

![2021-08-17 11_22_13-Window](https://user-images.githubusercontent.com/52528841/129700024-0ed743b8-39cf-4d56-84e9-0cf8d39fde67.png)

**Comment by Hofknecht** [comment]
- [x] Change solution to target framework .NET 5
 - [ ]  github pipeline workflow
 - [ ] azure pipeline for github releases
 - [ ] windows store package

**Comment by Hofknecht** [comment]
SkiaSharp should even .Net 6

link to error:
https://docs.microsoft.com/de-de/nuget/reference/errors-and-warnings/nu1202

just adding the references like described here
https://docs.microsoft.com/de-de/dotnet/standard/frameworks
e.g. to
<TargetFrameworks>netstandard1.3; netstandard2.0; portable-net45+win8+wp8+wpa81</TargetFrameworks>
leads to other errors and seems to be wrong

not sure how to solve this

**Comment by Hofknecht** [comment]
is running now with .Net 6 with version 1.0.27.1
