### ISSUE TITLE
[Feature] USB - Portable user.config and relative folder

### ISSUE THREAD

**Issue by blackcrack** [Hofknecht/SystemTrayMenu#158]
**Is your feature request related to a problem? Please describe.**
it call for a standard-folder with the Folder-Searcher, no possible for to use a folder
inside of the program folder with "./menu"
**Describe the solution you'd like**
a possible to use a folder in the program folder

**Describe alternatives you've considered**
an other Systray program who is possible for to use on a usb-sick .. ehh stick

**Additional context**
have nothing else to say *bs*

best :)

**Comment by Hofknecht** [comment]
i see the following todo
- [ ] allow to configure relativ path
- [ ] allow to add a config to folder. When local config exists use this instead the current one

**Comment by Hofknecht** [comment]
OddlyInspiring voted for this topic here

https://www.reddit.com/r/productivity/comments/n75dgs/systemtraymenu/gxcn1lj/?context=3

This is a pretty remarkable little tool. I'm a software dev and SRE and Ive been trying for so long to find a newer, minimal launcher that's customizable. Quick question, is there any way to sync configuration between machines or export config? Nice work

I think we will put it into optionsmenu, there you can then change the path of config


at current version it is here
%userprofile%\AppData\Roaming\SystemTrayMenu

To find the user-<hostname>.config:
Contextmenu click "Log File". Log File will open in Notepad. In Notepad then click File -> "Save As ...". Copy the path from the FileBrowserDialog and paste in windows explorer


something to read from stackoverflow
https://stackoverflow.com/questions/982354/where-are-the-properties-settings-default-stored


make sure when changing here that we are allowed to save e.g. see here
https://github.com/Hofknecht/SystemTrayMenu/issues/120

**Comment by Hofknecht** [comment]
![image](https://user-images.githubusercontent.com/52528841/117571647-be28dd00-b0cf-11eb-8e75-6e733983beb1.png)

@blackcrack 
just finished, now it is possible to have a relative folder and portable config
inluded in version 1.0.17.40
https://github.com/Hofknecht/SystemTrayMenu/releases

thank you for the hints
