### ISSUE TITLE
[BUG] FileLoadException: Could not load file or assembly 'System.Drawing.Common, Version=4.0.2.2

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#165]
Thank you Ralf and Timohy for reporting 

SystemTrayMenu Bug reported 1.0.17.24

System.IO.FileLoadException: Could not load file or assembly 'System.Drawing.Common, Version=4.0.2.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)File name: 'System.Drawing.Common, Version=4.0.2.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive) at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark 

---

- [x] analyze, maybe .net version? write both users to ask version
- [ ] wait for answer from the 2 users
- [ ] put info as FAQ

**Comment by Hofknecht** [comment]
at the moment i can not reproduce

i found this
https://github.com/JanKallman/EPPlus/issues/594
here the solution was
4.5.3.2 has the above problem,i downgrade to 4.5.3,it works well.

---
Press Windows + R.
Type cmd.

**check .net core verison**
dotnet --version
`3.1.301`

**check .net version**
reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP"
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\CDF
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0
```
---

**Comment by Hofknecht** [comment]
Thank you Jean-Pierre for reporting

until now 3 user reported the bug

**Comment by topeterk** [comment]
Found also this one: https://docs.microsoft.com/en-us/troubleshoot/dotnet/framework/manifest-definitions-do-not-match-reference

**Comment by Tanjalibertatis** [comment]
It is occuring on this pc here, also in debug and reproducible when opening settings, see here
![image](https://user-images.githubusercontent.com/62262740/117568932-63898400-b0c3-11eb-8e5f-fc9851c3ac4d.png)

not depending on framework because same output for framework with these commands
![image](https://user-images.githubusercontent.com/62262740/117568931-5f5d6680-b0c3-11eb-8062-1cc456954023.png)

even shown in debugger when try to select designer
![image](https://user-images.githubusercontent.com/62262740/117568989-a3e90200-b0c3-11eb-9167-5e873d8a0063.png)

**Comment by Hofknecht** [comment]
we got feedback from 1/3 users 
```
Merci pour votre message !
J'ai résolu le problème.
J'ai désinstallé complètement votre programme, puis je l'ai réinstallé !
Et il fonctionne très bien !
Encore merci !
```

=> seems to solve the problem
