### ISSUE TITLE
[BUG] Fix ArgumentException: Illegal characters in path

### ISSUE THREAD

**Issue by kehoen** [Hofknecht/SystemTrayMenu#171]
**Is your feature request related to a problem? Please describe.**

This is not so much a problem, but I would like to use this tool with network locations. At present, it will only show the network location shortcut and not populate any files or directories within.

**Describe the solution you'd like**

Cache or otherwise incorporate the network location file structure so it can be searched using this tool.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Hofknecht** [comment]
@kehoen  Thank you for the feedback!

![image](https://user-images.githubusercontent.com/52528841/117687864-834ea400-b1b8-11eb-8d6b-0476ab4e8e8a.png)
![2021-05-10 18_03_38-Window](https://user-images.githubusercontent.com/52528841/117689506-1b00c200-b1ba-11eb-8dae-5ca702bc8f78.png)
![2021-05-10 18_03_46-Window](https://user-images.githubusercontent.com/52528841/117689514-1d631c00-b1ba-11eb-99b1-f3e4563941ea.png)

yes, SystemTrayMenu should work with network locations e.g. here in screenshots.

i understand you have a shortcut to a network location (like screenshot 2) which is then not filled, when you hover over it or even click on it. There is even not a empty menu with "Access denied" or "Empty Folder" ?

Maybe you can provide us a screenshot that we can better imagine this. For this I could recommend the tool screenshot or it is also possible with snipping tools.
Addionally the logfile would be great, if the command fails we are logging it.

you could try the following manually:
start: cmd
with input: net view hostname
![image](https://user-images.githubusercontent.com/52528841/117690350-0bce4400-b1bb-11eb-8981-d596880d184b.png)
this command we are using internal, maybe there are problems with this command at specific systems or enviroments like domaincontroller, can you send us this output from your machine?

**Comment by kehoen** [comment]
Sorry for the delay. When I first filed the feature request, I was setting my shortcut as a "network location." When I did this, I wouldn't see any folders using the application - it would just have a single shortcut that when clicked would open a webbrowser.

After reading these posts, I set the shortcut to be a mapped network drive. Now, when using the application I get an error:

![image](https://user-images.githubusercontent.com/51907350/118246098-8e7f2980-b46f-11eb-9784-060a69c9a777.png)

"System.ArgumentException: Illegal characters in path. (Parameter 'path')   at System.IO.Path.GetFullPath(String path)   at System.IO.File.GetAttributes(String path)   at SystemTrayMenu.Utilities.FolderOptions.IsHidden(String path, Boolean"

If it makes any difference, the network location I am trying to access is a SharePoint site.

**Comment by Hofknecht** [comment]
Hello Kehoen, 

thank you for feedback and screenshots, now i see the problem

see screenshot, it seems it fails at line 68 (in my screenshot it is working here)

![image](https://user-images.githubusercontent.com/52528841/118255785-f30ca980-b4ac-11eb-8d28-e082bc8660bd.png)

we could add the ArgumentException to the catch to fix it

**Comment by Hofknecht** [comment]
@kehoen just released that fix. Please try with that new version 1.0.17.42
https://github.com/Hofknecht/SystemTrayMenu/releases

Waiting for feedback before close.

Thank you!!

**Comment by kehoen** [comment]
Thanks for the quick work, but it does not seem to totally fix the issue. I can now hover on the shortcut, but I can't see any directories:
![image](https://user-images.githubusercontent.com/51907350/118298282-47b02480-b4ad-11eb-8174-ad8196dbd510.png)

Further, if I try to access a sub-directory, I get this:
System.NullReferenceException: Object reference not set to an instance of an object.   at SystemTrayMenu.Utilities.FileLnk.IsNetworkRoot(String path) in D:\a\1\s\Utilities\File\FileLnk.cs:line 56   at SystemTrayMenu.Business.Menus.GetData(BackgroundWorker worker, String path, Int32 level) in D:\a\1\s\Business\Menus.cs:line 274   at SystemTrayMenu.Business.Menus.<.ctor>g__LoadMenu|14_0(Object senderDoWork, DoWorkEventArgs eDoWork) in D:\a\1\s\Business\Menus.cs:line 57   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by Hofknecht** [comment]
@kehoen 
Thank you for the fast test and feedback. 

Maybe can you send us the part from the logfile? There we can see the path, maybe this could help to see that "Illegal characters in path", to understand it a bit better, at the moment i can still not reproduce.

**Comment by kehoen** [comment]
Morning.

Here is an example from the log file on the crash:

```
2021/05/14 16:10:53.734 4  WARN path:'Z:\TCRP ' System.ArgumentException: Illegal characters in path. (Parameter 'path')    at System.IO.Path.GetFullPath(String path)    at System.IO.File.GetAttributes(String path)    at SystemTrayMenu.Utilities.FolderOptions.IsHidden(String path, Boolean& hiddenEntry) in D:\a\1\s\Utilities\FolderOptions.cs:line 67
```

There are lines of this for most (all?) of the folders. It doesn't seem to show in the copy/pasted code above, but perhaps it is the space at the end of the string? See snip from notepad:

![image](https://user-images.githubusercontent.com/51907350/118487741-05732700-b6e9-11eb-87b1-559a00240300.png)

**Comment by Hofknecht** [comment]
@kehoen
Thank you for the detailed informations.

It seems the problem is the invalid character at the end. this "NUL"

https://en.wikipedia.org/wiki/Null_character#:~:text=In%20documentation%2C%20the%20null%20character,null%20character%2C%20U%2B0000.

in code i can add e.g. \0 then i get the same exception

but e.g. if i create a folder with unix e.g. mkdir test\0 then windows is changing the name so that e.g. windows explorer can resolve it
![image](https://user-images.githubusercontent.com/52528841/118536308-da6def00-b74b-11eb-96e2-a65ba45e993d.png)

e.g. here is interresting
https://gist.github.com/doctaphred/d01d05291546186941e1b7ddc02034d3
"in general, the only forbidden charactersin filenames on Unix-like systems appear to be the forward slash (/) and the null byte."

we found no way to generate such a folder with a NUL

We tought to maybe implement just solution from https://stackoverflow.com/questions/146134/how-to-remove-illegal-characters-from-path-and-filenames without any test and let you try but the problem is for the full path it removes also \ between folders, so it is no full solution there only for filenames. and i'm still not sure if this NUL is in Path.GetInvalidPathChars() and with which character to replace it. And maybe if it is already a space because we see this in logfile and maybe it would be just enough to make a Trim() to the path. 

Maybe 3 furtther questions:
-Do you maybe know how to create such a folder, how we can repproduce this?
-Do you have windows 10?
-How does it look like in windows explorer. Is the correct folder in your case "Z:\TCRP" and its context maybe something like Z:\TCRP\filexyz.txt ?

**Comment by 405vzfe** [comment]
Maybe 3 further questions:
-Do you maybe know how to create such a folder, how we can reproduce this?

This happens for all of my mapped network folders (these are SharePoint site folders). They open fine in Windows Explorer.

-Do you have windows 10?

Yes.

-How does it look like in windows explorer. Is the correct folder in your case "Z:\TCRP" and its context maybe something like Z:\TCRP\filexyz.txt ?

![image](https://user-images.githubusercontent.com/84291770/118733846-216ee980-b80b-11eb-9a23-6451ba9db800.png)

But also, before clicking on the address in windows explorer, i see this:
![image](https://user-images.githubusercontent.com/84291770/118733945-524f1e80-b80b-11eb-808f-7fedc69ce877.png)

**Comment by Hofknecht** [comment]
Thank you for your patience

Idea with Trim() is not good e.g. you can add spaces at the end of foldername (e.g. with Alt + 0160)
![image](https://user-images.githubusercontent.com/52528841/119027451-a04c5980-b9a6-11eb-9be7-c6e2e28ca800.png)

here i found some informations about Notepad++ with special character NUL
https://www.xspdf.com/resolution/1623402.html
so i assume the character is: 
\x00

![image](https://user-images.githubusercontent.com/52528841/119027199-582d3700-b9a6-11eb-9c51-9004cb838429.png)

but when creating a folder or file with that windows resolves it also like in the other cases to a own name, which works
![image](https://user-images.githubusercontent.com/52528841/119027245-667b5300-b9a6-11eb-8f57-4f586fc1d955.png)

so i can still not reproduce, but we can make a try with replacing \x00

therfore added the follwing to code 
string directory = directoryWithIllegalCharacters.Replace("\x00", string.Empty);

and build new release 1.0.17.43
https://github.com/Hofknecht/SystemTrayMenu/releases

in case it not works we can look into logfile with hexeditor, therefore you can upload the logfile here (basically only that line needed included the special NUL character)

**Comment by kehoen** [comment]
Thanks! This new version now allows me to access the shared drive folders. The files within the folders still show up as blanks, but I can navigate the directory structure which works well enough for me. I appreciate all of you help on this.

**Comment by Hofknecht** [comment]
@kehoen 

added same solution also for files

1.0.17.44

just released 
https://github.com/Hofknecht/SystemTrayMenu/releases

If there are any more issues please don't hesitate to reopen this issue or open new one or contact us again


Thank you for helping to improve the SystemTrayMenu
