### ISSUE TITLE
[BUG] COMException (0x8000FFFF) at FolderBrowseDialog.NativeMethods.IFileDialog.GetResult

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#174]
Thank you Erwin S. for reporting 

System.Runtime.InteropServices.COMException (0x8000FFFF): Schwerwiegender Fehler (0x8000FFFF (E_UNEXPECTED))   at SystemTrayMenu.UserInterface.FolderBrowseDialog.NativeMethods.IFileDialog.GetResult(IShellItem

Found here:
https://social.msdn.microsoft.com/Forums/en-US/6ac8c460-4cb1-4188-8b90-071672dc54d6/error-systemruntimeinteropservicescomexception-0x8000ffff-catastrophic-failure?forum=sqlreportingservices

Maybe it is related to lower memory or that many files or folders were shown in FolderBrowseDialog or due to some update from windows 7 to windows 10 or system recovery. Needs further investigation.

**Comment by topeterk** [comment]
Maybe better to replace this native call with a managed version like: [https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.openfiledialog?view=net-5.0](https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.openfiledialog?view=net-5.0) ?

**Comment by Hofknecht** [comment]
We had a look together into google, it seems to be probably not possible to have the same look, it would only work with folderbrowserdialog which looks different. There are also other solutions like http://csharphelper.com/blog/2018/11/use-a-standard-windows-dialog-to-let-the-user-select-folders-in-c/ but we are not sure if this is better because we would include a lot of sub references with it

At the moment i think it only happend once so seems to be rare and probably der are other root causes for this.

we wrote Erwin and asked for informations

```
Hello Erwin,

Thank you for your feedback, we opened a bug:

https://github.com/Hofknecht/SystemTrayMenu/issues/174

Unfortunately I cannot reproduce the bug (yet) and would like to ask you how you did it; )

- Does the bug occur once or often or always? In which situation (s) did he occur? Probably after a folder has been selected in the FolderBrowseDialog? Was there anything noticeable about it, e.g. that many folders / files were shown / selected or another program was running while?

-Do you have Windows 10? Was this upgraded from Windows 7 or was a system restore performed?

- How much RAM do you have? You may also be able to check how much is being used in the TaskManager:

-Have you ever encountered the 0x8000FFFF error in any other program or in Windows updates?

- Unfortunately I still have a bug in there that the exception is cut off in the mail, you can possibly go to the logfile, right click on the STM icon in the system tray and then search for the logfile and there for COMException and send me the rest of the exception. That would help me a lot. If you send me the entire log file and there are personal data there, I will of course delete the log file after processing.


Thank you for helping us to improve the SystemTrayMenu!
```

**Comment by Hofknecht** [comment]
Did not receive feedback yet, but i could reproduce with visual studio when making double click on designer i got:
![image](https://user-images.githubusercontent.com/52528841/120062015-29772680-c060-11eb-817c-6a31ccd6aa2b.png)

and it was solved when restarting visual studio, which means it happened very probably once and is solved by a restart of application.

Probably very rare error, probably no solution because root cause not in SystemTrayMenu, probably ok because also workaround just a restart of app 

=> we will close this for now, let's wait if this happens again and maybe in later .net versions we can replace the FolderBrowseDialog
