### ISSUE TITLE
[Feature] Option to choose own icon

### ISSUE THREAD

**Issue by HansieNL** [Hofknecht/SystemTrayMenu#176]
It would be great to have the option to choose my own icon for SystemTrayMenu what will be shown on the taskbar.

**Comment by Hofknecht** [comment]
yes accepted ; )

**Comment by Hofknecht** [comment]
Set an icon like shown in the screenshot
![image](https://user-images.githubusercontent.com/52528841/120925084-1d7e0b00-c6d7-11eb-8039-d68416d7a070.png)

Find the new option (default disabled) here in Settings -> General -> Folder -> [ ] Use icon from folder
![image](https://user-images.githubusercontent.com/52528841/120925111-4d2d1300-c6d7-11eb-8766-c3d7878cc928.png)

in next release version 1.0.17.63

**Comment by Gitoffthelawn** [comment]
It would be great to add this to the FAQ!  If so, the above screenshots need to be updated, because the option is now in a different tab within STM's settings.

Also, is it fine to *not* assign a custom icon to the folder (IOW, just use the default folder icon)?
