### ISSUE TITLE
[BUG] Sometimes error on right click on the Icon in SysTray

### ISSUE THREAD

**Issue by Dtrieb** [Hofknecht/SystemTrayMenu#186]
Look Screenshot

 - OS: [Microsoft Windows 10]:
 - STMVersion [1.0.17.52]
![SystemTrayMenu_2021-06-06_14-19-50](https://user-images.githubusercontent.com/3650284/120924149-84e58c00-c6d2-11eb-9a4a-7b76d4c73924.png)

**Comment by Hofknecht** [comment]
thank you for reporting, i also regonized it and suppressed it by 

Revision: e10620f717df1b5fba4dfc356d6040af66043127
Author: Markus Hofknecht <Markus@Hofknecht.eu>
Date: 03.06.2021 15:00:53
Message:
[Feature] Custom Scrollbar (#183), version 1.0.17.58

----
Modified: Business/Menus.cs
Modified: Properties/AssemblyInfo.cs
Modified: UserInterface/CustomScrollbar/CustomScrollbar.cs
Modified: UserInterface/Menu.Designer.cs



   ```
         dgv.DataError += Dgv_DataError;
            void Dgv_DataError(object sender, DataGridViewDataErrorEventArgs e)
            {
                // WARN Dgv_DataError occured System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Icon'
                // => Rare times occured (e.g. when focused and close other application => closed and activated at same time)
                Log.Warn("Dgv_DataError occured", e.Exception);
            }

```


will be in next release

**Comment by Hofknecht** [comment]
try version 1.0.17.63
