### ISSUE TITLE
[Feature(s)] High resolution compatibility

### ISSUE THREAD

**Issue by iJahangard** [Hofknecht/SystemTrayMenu#188]
In high resolution displays ,the way that menus look like is not really interesting

It is will be nice if we will be able to set height of riws and search box 
and also icon sizes in regular 16 20 22 24 28 32 36 40 48 pixels

And also text size to

**Comment by Hofknecht** [comment]
Thank you for your feedback!

Basically it should work over Settings "Make everything bigger
![2021-06-08 17_39_53-](https://user-images.githubusercontent.com/52528841/121217963-9c637700-c882-11eb-9384-a5c9cf8b49d3.png)
![2021-06-08 17_45_19-](https://user-images.githubusercontent.com/52528841/121217968-9cfc0d80-c882-11eb-873e-34a78476185e.png)

BUT "Make text bigger" is not working
![image](https://user-images.githubusercontent.com/52528841/121218410-ffeda480-c882-11eb-8e78-ea1f0cfea681.png)


Also for the search and options we can improve.

**Comment by iJahangard** [comment]
Thank you for responding

I (& perty much anyone) do prefer use 100% screen scale
Because of many of my apps looks better in that scale especially professional apps and some of menus 

So it'll be such a painful thing 😅
If we will be able to set those properties manually it becomes more valuable app

May someone doesn't like it even the display setting are in 1.5 scale

BTW selecting icon from folder is a good option but select it from any source can be good too

**Comment by Hofknecht** [comment]
thank you for the hint i was expecting that this is maybe not enough from root folder only, ok i see now also
 - [ ]  [Feature] select icon from any source

for the rest i understand the issues from first answer would fullfill the request, except maybe also adjust text size as option to overwrite this from windows
 - [ ]  [Feature] option to adjust textsize

**Comment by iJahangard** [comment]
About select icon:
It's better if you let the option of use root folder icon be 
It's really good for someone who's rus multiple of this app ( if it's possible lol)

Text size:
May it needs changing height of rows too

**Comment by Hofknecht** [comment]
multiple root menus/ several menus was also mentioned by @verdammt89x long time ago ; )

We could implement to have more AppNotifyIcon's and in option to define more than one menu, maybe in future. 
let's put a reminder here for this

 - [ ]  [Feature] multiple root menus

Thank you for all the hints here, we will come back to this topics and create issues from it later

**Comment by Hofknecht** [comment]
you find it here (version 1.0.17.66):

![image](https://user-images.githubusercontent.com/52528841/123541150-41b39180-d743-11eb-8833-b5605169e5c3.png)



putted [Feature] multiple root menus  to notes in project

=> closed

**Comment by iJahangard** [comment]
> you find it here (version 1.0.17.66):
> 
> ![image](https://user-images.githubusercontent.com/52528841/123541150-41b39180-d743-11eb-8833-b5605169e5c3.png)
> 
> 
> 
> putted [Feature] multiple root menus  to notes in project
> 
> => closed

Sweet thanks 😊
