### ISSUE TITLE
[Feature] Show how many folders and files a folder contains in searchbar

### ISSUE THREAD

**Issue by iJahangard** [Hofknecht/SystemTrayMenu#189]
It will be nice if you add a some metadata about how many folders and files are in the directory alongside with folder name

something like this:

**FolderX** 23 folders & 32 files

This may look better through bringing down the opacity of "folders and files part"

**Comment by Hofknecht** [comment]
@iJahangard
Thank you for feedback!

there might be not enough space in title for this (if i understand correct). There is also the case the the root folder has a longer name than its containing items. Of course we can shorten up the name, but depending for what.

Basically the windows explorer shows it in columns
![image](https://user-images.githubusercontent.com/52528841/121251683-700e2180-c8a7-11eb-8cb0-080e1f50fbb8.png)
and there are a lot of meta data there, this would be possible, but maybe a lot of efford exspecially the resize of columns and probably much more ... 

Maybe you can describe a bit more the idea, maybe in some screenshots ; )

**Comment by Hofknecht** [comment]
yes, thank you for that idea

in windows explorer it looks like this:
![image](https://user-images.githubusercontent.com/52528841/121555156-0ca10280-ca13-11eb-84ab-eb84f5839f5f.png)

so bottom is good, i also like the idea in the search because it gets updated by search
windows explorer shows only items, so we need to decide if to show both (files and folder) or only one and if as icon or text

but i like what you showed in screenshot i think we can make it like this

accepted 


Thank you!

**Comment by topeterk** [comment]
Funny, that there are multiple folder icons in Unicode, like 📁, but could not find any specific for files.

**Comment by iJahangard** [comment]
You are the main and the brain 😂
So you can make it looks like what you want

Make it customize-able is good too

Showing it in searchbox is the best ideal form
It looks formal if you do something like windows explorer 
╔═══════════════════╗
║Search.                       X.items     ║
╚═══════════════════╝
With the ability to choose showing or hide icon and text separately

What do you think? 🧐

**Comment by iJahangard** [comment]
> Funny, that there are multiple folder icons in Unicode, like 📁, but could not find any specific for files.

Use this repo for having a great collection of new design icons in ttf and svg formats

https://github.com/microsoft/fluentui-system-icons

Also will help system tray menu to make a customize-able search icon ( i mean for choosing colors of it in dark and lite mode)

**Comment by Hofknecht** [comment]
also fixed with this task a rare  minor bug: when a submenu is open, then change search and then move with arrows back to first menu, but the item not showing due to changed search
![image](https://user-images.githubusercontent.com/52528841/123544950-0bcbd880-d756-11eb-86e6-4837657eccb7.png)

**Comment by Hofknecht** [comment]
@iJahangard

implemented, now looks like this (version 1.0.17.69)
![image](https://user-images.githubusercontent.com/52528841/123546729-1db17980-d75e-11eb-9b1c-c1cba6294b63.png)

![image](https://user-images.githubusercontent.com/52528841/123546604-92d07f00-d75d-11eb-9f31-91120705815c.png)



will be in next release

**Comment by iJahangard** [comment]
Nice ! Will try and see what happens 😍
