### ISSUE TITLE
[Feature] Customize Color 'Border of Menu'

### ISSUE THREAD

**Issue by iJahangard** [Hofknecht/SystemTrayMenu#191]
It doesn't really looks good
Even in white theme you have to see that

Deleting or make it configurable can be so sweet
Thank in advance

**Comment by Hofknecht** [comment]
yes true the black border still missing to customize

**Comment by iJahangard** [comment]
Can't wait till you release new version ;)

**Comment by Hofknecht** [comment]
Thank you : )

just released https://github.com/Hofknecht/SystemTrayMenu/releases/tag/v1.0.17.68
including this feature

**Comment by iJahangard** [comment]
> Thank you : )
> 
> just released https://github.com/Hofknecht/SystemTrayMenu/releases/tag/v1.0.17.68
> including this feature

Oh man ! Such a good dev you are
 thank you ;)
