### ISSUE TITLE
[BUG] SystemTrayMenu.exe requires .Net 3.1.0 and not compatible with .Net 3.1.7

### ISSUE THREAD

**Issue by IAmSurajBobade** [Hofknecht/SystemTrayMenu#193]
**Description, Steps to reproduce, Expected behavior, Screenshots**

Please note 3.1.7 has some security patches on top of 3.1.0 - unless 3.1.0 is a must, can we remove this version-specific dependency?

Steps to reproduce:
<System has .Net 3.1.7 (latest) version installed (.Net 3.1.0 is not installed)>
- download latest SystemTrayMenu.zip
- Try to install the SystemTrayMenu.exe
- Windows throws below error: 
![image](https://user-images.githubusercontent.com/11486375/126451882-9de448c9-f864-4178-9978-031670daa004.png)

 - OS: Microsoft Windows 10 Home Single Language
 - Version	10.0.19043 Build 19043

**Comment by Hofknecht** [comment]
sorry for later answer, i did not yet found an answer to this question. 
i think there should be no version-specific dependency or at least i do not know where

in visual studio i can only select 3.1 
![2021-09-05 13_18_34-Window](https://user-images.githubusercontent.com/52528841/132124878-8251bd86-2c73-4cf6-83e1-338e5a2c3c09.png)

here is the downloadpage:
https://dotnet.microsoft.com/download/dotnet/3.1

latest is now 3.1.18

i installed latest version
![2021-09-05 13_21_48-Window](https://user-images.githubusercontent.com/52528841/132124949-76026f77-4975-4653-8185-0f4e9ca5176f.png)

and it is still running

so i have problems to reproduce this, i think 3.1 is always compatible to 3.1.xx

maybe i need to try on a fresh windows installation

**Comment by Hofknecht** [comment]
I think we close this for now, hard to reproduce and probably there is no fix possible from our site

Maybe we are switching to .Net5 in the future
