### ISSUE TITLE
[Feature] Select root folder by windows context menu

### ISSUE THREAD

**Issue by the-phuctran** [Hofknecht/SystemTrayMenu#195]
I have 2 root folders, they're both differnt in purpose of use. I wonder could this feauture be added for better arrangment and navigating. Thanks for your app, I'm now ready for jumping to Windows 11.

**Comment by Hofknecht** [comment]
Thank you for you feedback!

of course as workaround you can create a new root folder and put a link to each of them into it.
But i understand the idea to have really 2 instances or 2 icons or 2 shortcuts.

similar idea was mentioned in https://github.com/Hofknecht/SystemTrayMenu/issues/188 in comments by @iJahangard 
multiple root menus/ several menus was also mentioned by @verdammt89x long time ago ; )

should be possible to implement.

probably not several instances better implement it in one instance and with options

probably we should implement for n rootmenus/ icon/shortcuts, this means for optionsmenu the blue marked once needs to be n time there
![2021-09-20 17_19_53-Window](https://user-images.githubusercontent.com/52528841/134028640-fbca74f6-e84c-437c-bb6a-ff27bd632cd1.png)

maybe the "Use icon from folder" stays there one time, but there is the question how to differ the icons then or maybe combine with feature to select a icon
maybe the "Change to relative" stays there one time and affects all pathes

**Comment by the-phuctran** [comment]
I think we can have the _add folder as rootmenu_ button in File Explore context menu , if we want a folder to be a rootmenu in STM we can right click that folder in File Explorer and choose it to appear in the settings and customize it. The folder icon could use the default icon of the folder and people can change that from folder properties in File Explorer.

**Comment by Hofknecht** [comment]
that sounds good. I think this solution is easier than the others and could be done with adding a registry entry over options menu:
http://www.reza-aghaei.com/how-to-add-item-to-windows-shell-context-menu-to-open-your-application/
https://www.codeproject.com/Articles/10104/Add-a-context-menu-to-the-Windows-Explorer

**Comment by Hofknecht** [comment]
@the-phuctran 

find the option here
![2021-09-23 11_52_41-Window](https://user-images.githubusercontent.com/52528841/134488866-86219d67-af51-47aa-95de-9d8eb8aa0706.png)

then in context menu when right click a folder, the new method appear
![2021-09-23 12_02_55-](https://user-images.githubusercontent.com/52528841/134489188-c9a2a973-3356-4633-ba12-8ff4d924c8e4.png)

now it is also possible to forward the root folder by argument so you can create shortcuts to switch the root menu
![2021-09-23 12_05_04-Window](https://user-images.githubusercontent.com/52528841/134489436-f8e161c5-94fc-4724-b386-17744b8d9f53.png)
e.g. you could create a shortcut "switch to folder B" and place it into Folder A and a "switch to folder A" into Folder B

version 1.0.18.1

will be in the next release

**Comment by the-phuctran** [comment]
After I change the root folder to another one by context menu on UWP version, then the app looped into "Read the F&Q and then choose a root directory" box with the act of selecting the directory in file explorer. I also reinstall the app but problem still persist and everytime it shows file explorer window, it always starts with the folder that I have selected by context menu before.

**Comment by Hofknecht** [comment]
@the-phuctran 
can you try adding a file to the new root folder and check if this solved the problem.
i can only reproduce when e.g. folder empty or only folders in it
probably need to adjust this condition if this is the problem

if still not working would be good to check against last version SystemTrayMenu 1.0.17.68

thank you for reporting and your help

**Comment by Hofknecht** [comment]
@the-phuctran
(hopefully) fixed with https://github.com/Hofknecht/SystemTrayMenu/releases/tag/v1.0.19.0
also available as uwp in next day(s)
