### ISSUE TITLE
[Feature] Dark mode 

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#21]
We should add contextmenu item. 
Maybe extra dialogue, but then we can directly add a settings menu
or
selectable in the contextmenu like the languages

Can we read this dark mode also from windows?

Should we make it possible for the user to set MenuDefines e.g. from a xml?
=> This was also an idea before, but we want it as easy as possible for the user.

Do we need a bigger solution e.g. folder 'styles' & e.g. extra menu to select and/  or to preview it
It depends on how many styles we have and how complexe they are. Maybe only 4 values which are fix in code and only normal and dark so context menu enough?

**Comment by Hofknecht** [comment]
linked in [Archieve] #50

**Comment by Hofknecht** [comment]
TODO: still a issue, check if we can overtake windows styles

**Comment by topeterk** [comment]
I experience same issues with my Hit Counter Manager as I was introducing dark mode. Those colors are a pain, especially when you support multiple platform like me (Windows, Mono Linux, Mono Mac).

I guess I will use fixed own colors as getting this data from all these platforms will not be an easy task, especially with .Net 2.0 support that I am still trying to keep for compatibility.

For my application I was able to get the Windows 10 application dark mode settings this way:

        /// <summary>
        /// Read the OS setting whether dark mode is enabled
        /// </summary>
        /// <returns>true = Dark mode; false = Light mode</returns>
        public static bool IsDarkModeActive()
        {
            // Check: AppsUseLightTheme (REG_DWORD)
            // 0 = Dark mode, 1 = Light mode
            return Registry.GetValue("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize", "AppsUseLightTheme", 1).ToString() == "0";
        }

**Comment by Hofknecht** [comment]
check also if this helps
https://stackoverflow.com/questions/38734615/how-can-i-detect-windows-10-light-dark-mode


DarkModeOff.reg
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize]
"AppsUseLightTheme"=dword:00000001
```

DarkModeOn.reg
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize]
"AppsUseLightTheme"=dword:00000000


```

**Comment by Hofknecht** [comment]
ControlPaint.ContrastControlDark   maybe helps ?

**Comment by Hofknecht** [comment]
done
