### ISSUE TITLE
[Feature] Search all throughout the subfolders

### ISSUE THREAD

**Issue by blacksparrow15** [Hofknecht/SystemTrayMenu#211]
It is very much appreciated if you can type a keyword and then it will be filtered even if you don't hover or navigate through sub-folders, for ease of access and convenience. This is a very essential program for me since there is no folder toolbar yet for Windows 11 taskbar. Thank you!

**Comment by Hofknecht** [comment]
@blacksparrow15 thank you for the feedback!

The problem would be how long it takes to search. We do not store any menus and we do not build our own tree in any other way. So the architecture would be such that you simply browse folder by folder and then add them. I imagine that if nothing was found in the current menu, an item appears to search in all submenus only the next direct level. But that will take a few seconds. So actually a very nice feature but also very complex and still has to be thought through a bit, I'll put the tags: discussion and future extension

we will consider this in the future, needs more investigation

**Comment by blacksparrow15** [comment]
Thanks for the quick response. I appreciate it a lot. Yeah making this one a tickable option in the settings would be great. I have installed "Search Everything" by voidtools, and what they do is they index every file/folder first (for a few seconds/depending on what machine you are using) then the results are shown in an instant after typing a keyword.
![Screenshot 2021-10-10 223617](https://user-images.githubusercontent.com/68138232/136700302-a453d0f5-7866-4984-b456-0c59d6063248.jpg)

**Comment by Hofknecht** [comment]
@blacksparrow15 

yes, this is a great feature!

(Now i can select my games and url directly instead selecting first Games/URL folder, so double my speed to open it there ; )

i hope how we realized it will be fine for you. The user have to add the folders here

![2021-11-13 10_21_44-Window](https://user-images.githubusercontent.com/52528841/141613567-f2f1a7b5-0f3b-4a23-be5f-be2ab337daf0.png)

In this way the user have to really choose everything preventing him to add unintentionally too many 

Is now working fine in 1.025.8
so we will release it soon in 1.0.26, but latest at 1.12.2021

**Comment by blacksparrow15** [comment]
thank you very much for this feature! i love it and can't wait to download the latest build! kudos to your team!

**Comment by Hofknecht** [comment]
@blacksparrow15 just released 
https://github.com/Hofknecht/SystemTrayMenu/releases
