### ISSUE TITLE
[Feature] OS system shortcuts not translated

### ISSUE THREAD

**Issue by Tanjalibertatis** [Hofknecht/SystemTrayMenu#212]
Thank you for your feedback Peter O. !

Seems windows explorer translates some filenames e.g. 'Task Sceduler' with 'Aufgabenplanung'. In this cases we show the filename not the translated filename

![2021-10-09 20_04_33-](https://user-images.githubusercontent.com/62262740/136669490-45508533-1d5a-449c-9ceb-93ce410b7f75.png)

e.g. when copy the shortcut it takes some time until it is shown translated. e.g. when making a new shortcut and just name it 'Task Sceduler' it gets also translated even if not target the task sceduler. 
It looks like a fixed translation of the filename without checking other meta data of the file, but needs further investigation.

workaround: rename file manually into specific language

**Comment by Hofknecht** [comment]
The only possibility we currently see would be to translate all os system shortcuts individually into all languages. Because this would be too much effort, we would suggest that the user translates this for himself.
We don't see any other solution at the moment, so the issue is closed.
