### ISSUE TITLE
[BUG] Settings dialog doesn't show all elements

### ISSUE THREAD

**Issue by kristofzerbe** [Hofknecht/SystemTrayMenu#217]
A couple of days ago I made a pull request with the new feature "Open Folder" (https://github.com/Hofknecht/SystemTrayMenu/issues/206) in settings and was fiddling a bit around with the size of the settings dialog, because the content doesn't fit.

In the new version (10.0.21.0) I see that the new button is implemented in code, but it doesn't appear in the dialog and some of the elements at the bottom of the dialog are out of sight.

![systraymenu-settings](https://user-images.githubusercontent.com/243113/136808069-6ffd3159-02cd-4237-a618-6c98611b342a.png)

Interesting is the preview of the dialog in VS:

![systraymenu-preview](https://user-images.githubusercontent.com/243113/136808791-6312976a-323d-4c0c-a419-4d252a743e8b.png)

The new button "Open Folder" is completely out of sight and ``tableLayoutPanelChangeFolder`` as far to wide. I didn't get the problem solved. Is the button pushing its panel to its size or is the panel too wide? It is not possible to change the ``Size`` values of the panel. I guess it is the panel, because its ``Anchor`` is set to ``Left, Right`` and not to ``Top, Left``.

In general it is a problem with Windows Forms dealing with different scalings under Windows 10. When using my full resolution everthing is way too small, but the settings dialog has all elements.

 - OS: Windows 10 Pro, Version 10.0.19042 Build 19042
 - Resolution: 3840 x 2160
 - Scaling: 200%
 - Version: 10.0.21.0

**Comment by Hofknecht** [comment]
@kristofzerbe
Thank you for reporting the issue!

i assume/hope that is probably only a local change in designer in your cloned repository, as is looks normal at several devices on which i tested.

in your PR there were a lot of changes in the designer, which i reverted after, so i assume your visual studio version is re-adjusting/changing controls when you open the form over visual studio. Therefore maybe update visual studio to latest version.

can you try to download latest version, compiled here to compare it:
https://github.com/Hofknecht/SystemTrayMenu/releases/tag/v1.0.21.0

here a screenshot how it looks like in windows dpi size 100%
![2021-10-11 17_17_56-Window](https://user-images.githubusercontent.com/52528841/136815055-79277902-e413-459c-bc3b-2680c835f707.png)

![2021-10-11 17_18_57-Window](https://user-images.githubusercontent.com/52528841/136815153-1f62a1a4-3474-4098-9983-232a197b486c.png)
