### ISSUE TITLE
[BUG] Icon of .appref-ms (e.g. 'Cal4Desktop') not displayed correctly

### ISSUE THREAD

**Issue by Tanjalibertatis** [Hofknecht/SystemTrayMenu#218]
Thank you Peter O. for reporting that the icon of 'Cal4Desktop' is not displayed correctly!

**Comment by Hofknecht** [comment]
the root cause was we did not call the specifc function as STA thread.
seems .appref-ms always have overlay, so we added in code that for this extention to add always a overlay

**Comment by Hofknecht** [comment]
mail " Peter O." answered
