### ISSUE TITLE
[Feature] Option to set a position of the main menu

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#229]
@Ryonez mentioned in #13, that he wants to have  different position (not primary screen)
Peter O. mentioned via mail, that he wants to have different position (where the normal start menu appears at the bottom left)

The best thing would be if the user could simply move the menu via click on title bar and then drag drop to his favorite position. 
There should be a option to set a position of the menu.

**Comment by Ryonez** [comment]
I've created another issue that would be good to rectify while this is being worked on.
Currently, if you use the "Appear at mouse location" setting on a monitor, if it's to close to the edge where the two monitors "join", the menus can spill out onto the other monitor. Issue can be found here: #231

**Comment by Hofknecht** [comment]
Added a option to appear at the bottom left  (that's what Peter O. wanted)
![2021-11-09 18_31_59-Window](https://user-images.githubusercontent.com/52528841/140975431-68063bdc-2da3-45f9-be54-af2c94129591.png)

to drag drop is maybe to much and not necessary for now

(i am not sure if somewant wants to have the menu on another specific position than default button right, button left now as option. We could implement e.g. top left or top right or if necessary specific position by moving it there, if someone needs this just give me a hint )

that point from Ryonez we will implement in #231

so we can close this for now
