### ISSUE TITLE
[BUG] Menu Spills Over Across Monitors

### ISSUE THREAD

**Issue by Ryonez** [Hofknecht/SystemTrayMenu#231]
**Description, Steps to reproduce, Expected behavior, Screenshots**

If you use the "Appear at mouse location" setting on a monitor, if it's to close to the edge where the two monitors "join", the menus can spill out onto the other monitor.

Example
![image](https://user-images.githubusercontent.com/16157130/140605599-6da77e84-e60a-474a-b07f-cedf9d3fb243.png)

It would be a good idea to avoid this by constraining the menu to the monitor it is spawned on.

 - OS: Microsoft Windows 10 Pro
 - Version 1.0.25.0

**Comment by Hofknecht** [comment]
@Ryonez 
Thank you for the feedback!

yes exactly, it opens in the direction of the primary screen and there it would also take into account the edges of the primary screen. With the option to appear at the mouse position, the edges of the screen on which the menu appeared should be used

**Comment by Hofknecht** [comment]
we had here already the correct solution
![2021-11-09 18_50_12-Window](https://user-images.githubusercontent.com/52528841/140977500-ffdce7a7-2e38-4d83-b81b-0bbe879942ce.png)

and reverted it here
![2021-11-09 18_50_48-Window](https://user-images.githubusercontent.com/52528841/140977602-464c3a17-93e3-4ca4-9060-646bc9b4befd.png)


now it is working correct with 1.0.25.4
