### ISSUE TITLE
[BUG] Round Corners Fail to Show Outline

### ISSUE THREAD

**Issue by the-phuctran** [Hofknecht/SystemTrayMenu#238]
**Description, Steps to reproduce, Expected behavior, Screenshots**
There's no round outline if round corners turn on
![image](https://user-images.githubusercontent.com/43033446/141672807-5894ef66-fae2-403f-945f-526578474ed3.png)

 - OS: Windows 11 Pro, build 22000.346
 - Version 1.0.26.0

**Comment by Hofknecht** [comment]
thank you for reporting! oh we only tested on a black background, stupid that we turned it on as a default option. ok yes we will fix until next version!

**Comment by Hofknecht** [comment]
comitted something which fixes the issue with 1.0.26.2
(there was also a pixel location wrong, adjusted with 1.0.26.1)
![2021-11-14 10_52_37-Window](https://user-images.githubusercontent.com/52528841/141676253-8d94090f-4ea4-4d44-8f4f-4b4cb19b2ee9.png)


but the round corners looks not smooth. maybe we try to improve e.g. draw own corners like described here 
https://stackoverflow.com/questions/38632035/winforms-smooth-the-rounded-edges-for-panel

**Comment by Hofknecht** [comment]
https://github.com/Hofknecht/SystemTrayMenu/releases/tag/v1.0.26.2
made a hotfix release 

we will check if we can make it more smooth later
