### ISSUE TITLE
[Feature] Generate shortcuts to drives

### ISSUE THREAD

**Issue by vanjac** [Hofknecht/SystemTrayMenu#259]
I'd love to be able to select "This PC" as the target folder so I could get a drive list. I realize This PC isn't a real folder -- any way to show a list of drives which automatically updates would be useful. Right now I've made a folder full of shortcuts to each drive, but of course this doesn't update when I connect a new one.

**Comment by Tanjalibertatis** [comment]
Thank you for the feedback!

An option to 'Add all drives' sounds great! We would place the option (default off) as checkbox into option tabpage 'Folder'. (Therefore we will move the cache options to tabpage 'Expert').

When enabled we add all drives (which we get from https://stackoverflow.com/questions/781905/getting-a-list-of-logical-drives) to main menu.

**Comment by vanjac** [comment]
Yes, that would be perfect!

**Comment by Hofknecht** [comment]
@vanjac 

we implemented it, see here a screenshot of new option.
if it should check the drives every time, then just disable the option to cache the main menu 

![2021-12-10 15_17_39-Window](https://user-images.githubusercontent.com/52528841/145588434-e5272ed2-5024-41d7-9c4a-395188acc9f3.png)

**Comment by Hofknecht** [comment]
with #270 we moved the cache main menu option to expert tab, so find it there if you want to disable Cache main menu (if you e.g. want to see a USB stick that has just been plugged in without pressing the refresh buttonk)

(in the future we want to implement that changes are updated into cached menu)

**Comment by Hofknecht** [comment]
related mail:

Bernd B. reported via mail:

> System.UnauthorizedAccessException: Zugriff verweigert (0x80070005 (E_ACCESSDENIED))   at IWshRuntimeLibrary.IWshShortcut.Save()   at SystemTrayMenu.Utilities.GenerateDriveShortcuts.CreateShortcut(String linkPath, String targetPath)   at SystemTrayMenu.Utilities.GenerateDriveShortcuts.Start()   at SystemTrayMenu.Business.Menus.LoadMenu(Object senderDoWork, DoWorkEventArgs eDoWork)   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
> 
> Gesendet von Mail für Windows

our answer:

> Hello Bernd,
> 
> Thank you for reporting that bug!
> 
> It is related to Generate shortcuts to drives #259:
> https://github.com/Hofknecht/SystemTrayMenu/issues/259
> 
> We added a try catch to the line () with [BUG] Fix FileNotFoundException - Option GenerateDriveShortcuts - in case Windows Defender triggered #272:
> https://github.com/Hofknecht/SystemTrayMenu/issues/272
> 
> we will add your infos there.
> 
> is catched with version 1.2.0.3
> 
> we will release 1.2.1 in a few days.
> 
> This will only catch the exception and instead crashing it will log it as warning. There are probably missing rights to create these drive shortctus at the root folders location.
> 
> Maybe can you try to start STM.exe once as admin
> 
> 
> and check if the shortcuts are then generated without this access denied exception?
> 
> And maybe try another folder just for our information e.g. desktop.
> 
> Please let us know if something solved the issue.

![2022-01-06 21_15_50-net6 0-windows10 0 22000 0](https://user-images.githubusercontent.com/52528841/148461875-3820774a-8739-4e88-8648-b40ef2bbacea.png)
