### ISSUE TITLE
[Feature] Implement Recursive Searching

### ISSUE THREAD

**Issue by ParasiteDelta** [Hofknecht/SystemTrayMenu#273]
So, I decided to give this a go coming from Open Shell, since I figured that having a more Linux-esque pop menu for shortcuts and functions would be great. Other issues aside, there is one basic feature that needs to be implemented for this to be considered as a serious contender, and that is **recursive searching**.

I open Open Shell, start typing, and can find whatever I want or need regardless of file structure or said item being pinned.
I open the Windows Start Menu, start typing, and will either find it or get close enough.
I open STM, start typing, and _it won't even search one folder down from root for shortcuts or links_.

This alone makes this tool's utility pretty moot. The Windows 10 search function is notoriously bad, so anything is generally better, but to not even be capable of searching your chosen root recursively, let alone hotspots like your Desktop or Start Menu folders as secondary locations, kind of kills the use case for this tool, as everything must be manually managed, selected, and filtered with no assistance from the program itself.

**Comment by Hofknecht** [comment]
Thank you for that feedback!

This is very similar to https://github.com/Hofknecht/SystemTrayMenu/issues/211
There we solved it with this:
![2021-12-15 16_49_57-Window](https://user-images.githubusercontent.com/52528841/146221580-bd5e0587-6b81-48a3-8da0-f941de301a86.png)

you can configure which contents of folders to add to main menu

e.g. with the Add sample 'Start Menu' folder it will add there resursiv all content from:
C:\ProgramData\Microsoft\Windows\Start Menu

which is mainly what you expect hopefully.

In our roadmap we have a point to add possiblity to hide these addional entries.

Please try this solution and give us feedback if that worked for you.

Maybe this Start Menu folder should be default added.

Is this something which helps you or do you need something different.
The main issue is to cache let's say a complete drive recursivly, exspecially the icons foreach item, so we want to avoid this.
But we understand that point that it should default find things like normal start menu.

Lets discuss it further

**Comment by ParasiteDelta** [comment]
Eh, that actually solves it. I don't know if I was just overly exhausted when I first tried the app, but that's more or less on the right track. The particular issue that I should've clarified is that when I create a folder for the particular links or shortcuts to use as the root folder, the program does not appear to recognize any additional subfolders created within that root folder, not in the menu shown in the screenshot above or by default.

Say I make a folder, called simply 'shortcuts' and place it on the root of a different drive (D:, G:, whatever). I set this as the root folder for STM. If I make any further folders in that root to organize the shortcuts placed in the root, the program does not automatically parse these folders, and it does not display these folders in the menu shown above.

While the Windows Shell will never, ever compete with something like i3, AwesomeWM, or QTile, the main selling point for a launcher in any given GUI is the ability to recursively search and suggest based on criteria, or failing that, to recursively search and suggest a set folder(s) for links, programs, etc. These launchers are meant to be fast, concise, and yet friendly. It could simply be that I'm comparing this to something like Rofi or DMenu and was hoping for something like that on Windows, in which case, I apologize for the pointless threads.

**Comment by Hofknecht** [comment]
@ParasiteDelta 
Thank you very much!
The reason for this is simply performance. The user can decide whether he wants this and how deep he wants to search. Here we also have on the roadmap that if you show additional folder contents, you can still configure that this content is only found by searching and is not always displayed.

Your feedback helps us a lot at this point, because we often hear this expectation that it should be that way by default. The problem would be e.g. if you have a network shortcut there. Then the STM would first have to inquire about everything in the network, maybe/probably you don't want that as default.


That's great to hear for us, that this options solved that issue for you!

We're going to mark this as a FAQ so it can help and inspire others find this option too.

**Comment by Hofknecht** [comment]
@ParasiteDelta
we mentioned/added you in the readme's 'Thank you' section.
we are happy about every suggestion idea hint impression
more of that!😊
