### ISSUE TITLE
[BUG] Displays Both a Taskbar Button and a Tray Icon

### ISSUE THREAD

**Issue by ParasiteDelta** [Hofknecht/SystemTrayMenu#274]
![image](https://user-images.githubusercontent.com/19669733/146096979-3e145560-d14e-469c-afd6-3b73efdecaa9.png)
![image](https://user-images.githubusercontent.com/19669733/146097444-17992c56-becc-455f-be9b-031028fb2519.png)

Shows both a taskbar button and a tray icon even with no program windows pulled up.

--Download 1.2 release
--Extract to directory
--Run according to FAQ
--Issue arises

Windows 10 20H2
Build 19042.868

**Comment by Hofknecht** [comment]
Welcome @ParasiteDelta !
Thank you for the feedback!

How exactly do you imagine it, how would you have imagined it by default?


Spoiler / History / Current implementation:
With 1.2. we set option 'Show in Taskbar' default true, but you can disable 
![2021-12-15 16_39_31-Window](https://user-images.githubusercontent.com/52528841/146217328-f5418474-65c2-4329-ae4e-f4a72ed847e6.png)

In system tray it is always shown


Both the taskbar button and the tray icon have the same function to open the menu via click on it.
At the system tray icon there are further function with right click
![2021-12-15 16_43_18-](https://user-images.githubusercontent.com/52528841/146217742-48cfef92-8421-4f21-a2f9-0dfd99bfb022.png)

**Comment by ParasiteDelta** [comment]
Oops, I must've missed it somehow. As to most defaults that I've seen for other programs, if a program operates from the system tray or minimizes to the system tray, then it doesn't display on the taskbar, hence my confusion.

**Comment by Hofknecht** [comment]
@ParasiteDelta 
yes you are right, from this point of view it might be strange.
Definitly thanks for the hint, we need to know such impressions and can maybe consider in other changes in the future.

thanks for closing  : )

if you find more that appears unexpectedly please let us know again, gladly via a new issue

**Comment by phanirithvij** [comment]
I vote for the default behavior to not show it on the taskbar.

**Comment by Hofknecht** [comment]
@phanirithvij 
Thank you for the feedback, we changed it in #304
