### ISSUE TITLE
[Feature] Swipe scrolling on touchscreen

### ISSUE THREAD

**Issue by donaldaken** [Hofknecht/SystemTrayMenu#275]
Support scrolling the menu by swiping up or down on a touchscreen.

I like to use the touchscreen on my laptop, particularly for opening and switching apps. I love that I can make the menus a little bigger to be easier to tap on an app in the menu. Scrolling the menu would be much easier if I could swipe up and down the list, rather than drag the scroll bar.

**Comment by Hofknecht** [comment]
Hey @donaldaken!
Thank you for the feedback!
yes that's a issue we should do, @Tanjalibertatis mentioned this as well a week ago. expecially with surface there is kind of expectiation that scrollings works like this.

so we will do this very soon.

i think we need something like this:
https://www.youtube.com/watch?v=YWIhsBd6gH4

**Comment by Hofknecht** [comment]
@donaldaken

Ok it seems to be working just fine now. We thought about an option in the settings, that it could be turned off. To start with, let's just leave it as it is, with no option. One reason for the consideration is that the drag drop file from the stm (#34) is influenced by it, that doesn't always work then. But it always works if either there is no scrollbar or you pull out the file in the same line, without swipe scrolling. We think that it now works quite well in the combination. 

@the-phuctran FYI see the changes related to DragDrop

in next official release 1.2.1 (I'm not sure when exactly we will release, we think there will be a few more features)
