### ISSUE TITLE
[Feature] Framework Self-Contained & .Net 7

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#277]
Jan reported:
Just upgraded SystemTrayMenu to v1.20
Application asks for dotnet-runtime 6
Downloadlink presents dotnet-runtime-6.0.1-win-x64.exe
It appears SystemTrayMenu requires 
dotnet-**sdk**-6.0.100-win-x64.exe 
instead of 
dotnet-**runtime**-6.0.1-win-x64.exe

related
https://github.com/Hofknecht/SystemTrayMenu/issues/193

**Comment by ElDani82** [comment]
First time user here. This is still an issue today, although there's no need to install the full SDK if you're not a developer.

The application wrongly links to a download of the runtime called *Microsoft.NETCore.App 6.0.10*, but requires the following runtime to start successfully: *Microsoft.WindowsDesktop.App 6.0.10*.

Both of them are available for download from the Microsoft [download section](https://dotnet.microsoft.com/en-us/download/dotnet/6.0), where the core is simply called *.NET Runtime* and the correct variant is called *.NET Desktop Runtime*.

**Comment by Hofknecht** [comment]
@ElDani82 
Thank you for the feedback!

Not sure why it is necessary to install the SDK instead runtime, needs further analyses.

Related to this topic i found we can publish self contained
https://superuser.com/questions/1716891/you-must-install-net-desktop-runtime-6-0-4-x64-error

seems to work fine, then it is not more necessary to install addionally 
![2022-10-27 16_04_08-](https://user-images.githubusercontent.com/52528841/198307114-238ee806-7221-409e-adcf-7af328e82ae0.png)

i will reopen, let's see if we can improve here something

**Comment by Hofknecht** [comment]
ok we have now made this self contained which means it is no longer necessary to download a framework. no more message appears now

**Comment by Tanjalibertatis** [comment]
build pipeline failes
