### ISSUE TITLE
[BUG] Entering '[' in the search box results in a error

### ISSUE THREAD

**Issue by dao-net** [Hofknecht/SystemTrayMenu#286]
When I enter `[` in the search box at the top of the menu, I get the following error message:

![image](https://user-images.githubusercontent.com/88294342/148317086-3beb71b2-6282-433c-b923-19d1a5da2f93.png)

The stack trace is as follows (pasted here from the email draft which was opened after pressing 'Ja' in the dialog; I have no clue why it was truncated):

System.Data.EvaluateException: Error in Like operator: the string pattern '%[%' is invalid. at System.Data.LikeNode.AnalyzePattern(String pat) at System.Data.LikeNode.Eval(DataRow row, DataRowVersion version) at System.Data.DataExpression.Invoke(DataRow row, DataRowVersion version) at System.Data.Index.AcceptRecord(Int32 record, IFilter filter) at System.Data.Index.InitRecords(IFilter filter) at System.Data.Index..ctor(DataTable table, IndexField[] indexFields, Comparison`1 comparison, DataViewRowState recordStates, IFilter rowFilter) at System.Data.DataTable.GetIndex(IndexField[] indexDesc, DataViewRowState recordStates, IFilter rowFilter) at System.Data.DataView.UpdateIndex(Boolean force, Boolean fireEvent) at System.Data.DataView.UpdateIndex(Boolean force) at System.Data.DataView.SetIndex2(String newSort, DataViewRowState newRowStates, IFilter newRowFilter, Boolean fireEvent) at System.Data.DataView.SetIndex(String newSort, DataViewRowState newRowStates, IFilter newRowFilter) at System.Data.DataView.set_Sort(String value) at SystemTrayMenu.UserInterface.Menu.TextBoxSearch_TextChanged(Object sender, EventArgs e) at System.Windows.Forms.Control.OnTextChanged(EventArgs e) at System.Windows.Forms.TextBoxBase.OnTextChanged(EventArgs e) at System.Windows.Forms.TextBoxBase.WmReflectCommand(Message

I am using version 1.2.0.0 of SystemTrayMenu (latest from the app store as of today) on a Windows machine (version 21H2 Build 22000.376).

**Comment by Tanjalibertatis** [comment]
@dao-net thank you for reporting that issue! 
It should be solved now, see in next official release 1.2.1.

Thank you @topeterk for fixing it that fast!
