### ISSUE TITLE
[Feature] Option to set icon size

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#297]
Hello, firstly thank you so much for this wonderful application, It works fantastically and looks amazing. 

I would like it very much if the icon size of items in SystemTrayMenu could optionally match the icon size for the same items in Windows File Explorer.

Here is a screenshot to show the size difference at present.

![SystemTrayMenu icon size 3](https://user-images.githubusercontent.com/48499740/150126685-f94ebf40-a14d-4723-bda2-7d06dd7a4bf4.png)

I think this would really help seamlessly integrate your app with the Windows GUI. 

As many people may prefer the bigger icons, my idea is that this could be done by making the minimum default icon size or padding the same as Windows File Explorer and to have an "Icon size" adjustment on the "Size and location" tab in Settings.
Thanks for looking at this.

**Comment by Hofknecht** [comment]
@chip33 
Thank you for the feedback!

Configuring the size of the icons is a good idea, it's also on our internal roadmap. We'll push that up and do it right next.

**Comment by chip33** [comment]
Fantastic, thank you :)

**Comment by Hofknecht** [comment]
now implemented in version 1.2.2.4

it is possible to decrease the size and also to increase it 

find the new option here
![2022-01-22 15_44_15-Window](https://user-images.githubusercontent.com/52528841/150643189-e940acdd-7232-41c6-ad85-2f706ae87a30.png)

@chip33  
we added you to the thank you section and the about menu : )

closed

**Comment by chip33** [comment]
Thank you so much for doing this so quickly :)
