### ISSUE TITLE
[BUG] Search with multiple repeating characters

### ISSUE THREAD

**Issue by topeterk** [Hofknecht/SystemTrayMenu#30]
**Description, Steps to reproduce, Expected behavior, Screenshots**
Prepare a folder with the following contents:
- dolls
- dollar
- lol

Do the following steps:
- Type 'd' it will select '**d**olls'.
- Within a second type 'o' it will still select '**do**lls'
- Within a second type 'l' it will still select '**dol**ls'
- Within a second type 'l' it will still select 'lol' as 'l' was pressed a second time.  
At this point Windows explorer search will select '**doll**s'.

What is the intention by STM? @Hofknecht 
I was expecting "same" explorer behavior which means it should continue selecting '**doll**s'?

Issue relates to KeyPress() at SystemTrayMenuHandler.cs

**Comment by Hofknecht** [comment]
Yes should be exactly like in Windows explorer. Good example.
