### ISSUE TITLE
[BUG] Fix Disappears after relogin via rdp

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#307]
Thank you Nitin for your feedback here:
![2022-02-04 14_22_16-Rezensionen](https://user-images.githubusercontent.com/52528841/152536323-2cb0137f-70ab-4185-84be-0254f7add94c.png)

I found maybe the bug or some similar, when relogin via rdp, the menu is not more working and also the notify icon in system tray is missing. So only workaround is to set arg -r or to kill via task manager

it comes from the fact that we restart the STM in the event of a display change in order to apply any dpi changes to the menu.

We have already checked whether we can somehow read out the correct dpi value and compare whether it is really a dpi change, but we have not found anything that works.

So I think it's better to remove the logic for AppRestart.ByDisplaySettings() on SystemEvents_DisplaySettingsChanged. The user can restart himself if dpi changes.

**Comment by vanjac** [comment]
Would connecting/disconnecting an external monitor also trigger this? I'm not using RDP but the icon keeps disappearing and I think it happens when switching monitors.

**Comment by Hofknecht** [comment]
@vanjac 
Thank you for the feedback!
yes, it was restarted at ByDisplaySettings which triggered the issue.
so if you have the same behavior that system tray icon disappeared after monitor change than it is the same.

if you want to you can try latest version (maybe build it via visual studio 2022) and give us feedback if it solved your issue

**Comment by vanjac** [comment]
I just got to try the newest update, and yes, that solved the problem. Thank you!
