### ISSUE TITLE
[Feature] Option to turn off menu fading

### ISSUE THREAD

**Issue by vanjac** [Hofknecht/SystemTrayMenu#310]
Based on #20 it seems like if I turn off "Fade or slide menus into view" under Windows Performance Options, this should also stop the SystemTrayMenu fade animations. But this doesn't seem to do anything, unless I'm misunderstanding how that feature is supposed to work. The menu fades are still there.

I already have "Time until menu opens" set to the lowest possible setting (20ms). Trying to get the menus to show up as fast as possible.

![image](https://user-images.githubusercontent.com/8228102/152602246-ac84d342-2a10-4aad-af6d-8b1b47ea9ad0.png)

**Comment by Hofknecht** [comment]
@vanjac 
addded some code that there is now a new option (only in code)

for testing you can change the code here that is returns UseFading false
```
public bool UseFading
        {
            get
            {
                //return ((bool)(this["UseFading"]));
                return false;
            }
```

especially via rdp disable the fading probably looks better.

I wanted to make an option for this on/off, but then we'll see if we can also read the option from windows

**Comment by Hofknecht** [comment]
@vanjac 
Added here a option 'Fading'
![2022-02-04 23_40_47-Settings](https://user-images.githubusercontent.com/52528841/152612865-b6b81e6b-cfbc-4d1c-a014-6c3764a6d794.png)
with which you can now disable (default enabled/true) the behavior in 1.2.3.5

Did not found the related windows registry key and not sure sometimes read registry keys triggers virus defender so maybe it is fine like it is now
