### ISSUE TITLE
[Feature] Put all language files in sub directory

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#314]
As STM is a portable application and gets moved around between directories or after compiling it would be neater if all the language files were in a subfolder "Languages" or "langs" or some name like that.

**Comment by Hofknecht** [comment]
@chip33 
Thank you for that feedback!

Yes, we even thought of that before, but then we didn't want to change anything about the automatic generation and we dismissed the topic. But it's very good that you bring it back to the table, yes we'll tackle that.

**Comment by chip33** [comment]
This probably is not a very important fix or use of your time, it was just something I noticed as I have been moving STM around quite a bit testing it in different locations.

**Comment by Hofknecht** [comment]
solved with 1.2.6.3 via post build event, works when rebuild locally.
we need to see if the azure pipeline makes it also correct.

meanwhile closed

**Comment by Hofknecht** [comment]
@chip33 
https://social.msdn.microsoft.com/Forums/vstudio/en-US/559d2411-fc28-4317-9a65-1912edf243af/changing-output-folder-for-language-resource-dlls?forum=vclanguage
> Technically it is possible, but you can't use the built-in ResourceManager anymore.  You'll have to assign the localized strings yourself after resolving the satellite location.  That's beyond painful in but the most trivial kind of cases.

is not that easy as i tought, reverted wrong made changes.
(But we changed that at least in the solution the languages are in are subdirectory)

we need a new tag 'Won't fix' : ), let's focus on the other issues first.

but if anyone else has an idea how to best do this, please let me know.
