### ISSUE TITLE
[BUG] Exception when right click shortcut to drive C: or D:

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#33]
**Description, Steps to reproduce, Expected behavior, Screenshots**
when i make a right click on shortcut to drive C: or D: i get an exception, see screenshot 
![rightclick c sometimes exception](https://user-images.githubusercontent.com/52528841/62409932-cd1b5b00-b5de-11e9-804d-f7ceb7b0326f.PNG)

message is shown interally (not throwing any exception to STM, so nothing in logfile) in 
int nResult = _oContextMenu.QueryContextMenu(
                    pMenu,
                    0,
                    CMD_FIRST,
                    CMD_LAST,
                    CMF.EXPLORE |
                    CMF.NORMAL |
                    ((Control.ModifierKeys & Keys.Shift) != 0 ? CMF.EXTENDEDVERBS : 0));

problem is solved when right click on other folder or shortcut, then exception not more happens (until restart).
Can the code solution be that we call it with fake/stub data (like in the manual workaround)?
What is the root cause for the error message?

 - OS: Microsoft Windows 10 Pro
 - Version: 0.9.1.251

**Comment by Hofknecht** [comment]
not happening on all Systems e.g. not at Tanja's PC

**Comment by Hofknecht** [comment]
@blubario @topeterk  can you test if that happens on your systems also, or is it only my pc?

**Comment by topeterk** [comment]
@Hofknecht tried this on my machine but no issue seen. Tested with shortcut to drive C:\ (physical SSD) and R:\ (virtual RAMDisk), both work.
In the screenshot I wonder that the error is shown for a VMWare DLL with ordinal 381. I guess you have anything installed in your explorer context menu related to virtual machines that may fail?
I have VMWare Workstation Player 12 installed and the function is available in my DLL which is `??1TListviewHeader@xui@@UAE@XZ` but this doesn't sound anything special.
So, for me this sounds like a general installation issue of your VMWare product?

**Comment by Hofknecht** [comment]
ok ty, will close the issue
