### ISSUE TITLE
[Feature] Improve icon

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#337]
>  icon is too pale ( #147)

> Looks like a flower.  (mentioned in youtube video)

---

it's supposed to be a tree! and yes on a windows light mode i can not see it because it is too pale!

original task to create icon (i still love the original one, but it just a common web menu icon before)
https://github.com/Hofknecht/SystemTrayMenu/issues/75 

we should redesign it or create a new one!

**Comment by Tanjalibertatis** [comment]
I like the idea of redesigning our current icon!
See my present drafts, but the problem with all three is that they are not easily recognizable in the small format and that the color should match both a light and a dark background:
![1](https://user-images.githubusercontent.com/62262740/154140370-3c5282e7-e9a7-4549-83ff-379818d03ab1.png)
![2](https://user-images.githubusercontent.com/62262740/154140386-112b92ed-6ecb-4f88-80d5-a7e2d07a17ce.png)
![3](https://user-images.githubusercontent.com/62262740/154140402-7b2d86c8-529c-4ccd-9076-5938523b73fe.png)

**Comment by Hofknecht** [comment]
maybe 3 leaves/branches instead of 5
![2022-02-15 21_19_55-Window](https://user-images.githubusercontent.com/52528841/154142582-485947f7-ff16-4330-bb75-fcb9e80f8644.png)

**Comment by Hofknecht** [comment]
or maybe like the "icon" from the classic desktop toolbar?
![2](https://user-images.githubusercontent.com/52528841/156899812-7cbab554-fc9a-4021-8a32-075d550c6691.png) 
![2](https://user-images.githubusercontent.com/52528841/156899802-b09f0846-e007-47c1-a328-d8247cbcae12.png)

**Comment by Tanjalibertatis** [comment]
![9](https://user-images.githubusercontent.com/62262740/156931569-4e4e33cd-15aa-47af-bb77-b4aed4e078c8.png)

**Comment by Hofknecht** [comment]
@doterik 
Do you mean the grey or the blue one? We improved the blue one (slighty other blue and smoth corners) and created a *.ico (includes all sizes from 16x16 to 256x256)
![A](https://user-images.githubusercontent.com/52528841/157383389-06d3d5db-9239-43e7-a78f-01081e4f9e45.png)
[A.zip](https://github.com/Hofknecht/SystemTrayMenu/files/8212152/A.zip) (contains A.ico)

Are there any further things we should still improve at this icon there or can we take it as it is now?

We should be very sure about this, because it will be very time-consuming to change this on the pages or some pages will not adapt it, so we could e.g. still display addionally the old icon on the github page

Since the icon changes completely, we lose a piece of the brand. But I think the new connection between the icon and the desktop toolbar is very good. and the problem that it cannot be seen on the light mode taskbar is also solved.

**Comment by Hofknecht** [comment]
to generate all levels i used 
https://www.aconvert.com/icon/

**Comment by Hofknecht** [comment]
![2022-03-10 00_11_21-Window](https://user-images.githubusercontent.com/52528841/157554736-1237a6ef-62d0-4c76-8604-d128dd850d34.png)
[A4.zip](https://github.com/Hofknecht/SystemTrayMenu/files/8218855/A4.zip)

**Comment by Hofknecht** [comment]
more dark, now it final:
![2022-03-11 19_40_49-Hofknecht_SystemTrayMenu_ SystemTrayMenu - Browse and open your files easily](https://user-images.githubusercontent.com/52528841/157931860-b9b249d6-c98e-4b26-8590-ee0f1fc4e4ed.png)


created new pictures and animation in readme with  new icon

now we need to adjust all other sources

**Comment by doterik** [comment]
After a long time, I started STM today and did an update 😎

I'm so happy with the new icon that I may try STM again (although I had a customized icon before (the old arrows))...

👍🏼
