### ISSUE TITLE
[Feature] DragDrop a file into a application

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#34]
Bob told he want to have the files like on the desktop, there he move a file on a shortcut to open the file with the application (which is opened by the shortctu)

**Comment by Hofknecht** [comment]
linked in [Archieve] #50

**Comment by Hofknecht** [comment]
TODO: rethink about issue

**Comment by Tanjalibertatis** [comment]
just a idea: we could also keep the menu open maybe with a pin in the top right, which the user can toggle. Then the user can drag drop things into the stm

**Comment by Hofknecht** [comment]
i think, we not want to disturb user with drag drop
for drag drop the user could open windows explorer folder by double click on folder 

won't implement for now

**Comment by the-phuctran** [comment]
You should reconsider about adding this feature, folders on windows 10 taskbar's toolbar can do this and it really saves the time. Less opened windows and handy drag & drop with shortcut are better, I don't find any disturbance when drag & drop on files in Windows toolbar, should give it as the option in the app setting.

**Comment by Hofknecht** [comment]
@the-phuctran  
thank you for feedback!

here i made a short video about the orginal drag drop issue the user wanted to have. 
e.g. on the desktop it is possible to open e.g. a picture by moving it onto e.g. paint.
The only way i see is on the desktop e.g. in windows toolbar drag drop has there a different function to drag drop the file above or below the other file. This was original the reason we denied to implement because it is also not in the windows toolbar
https://user-images.githubusercontent.com/52528841/134032897-349cddcd-436e-4427-bc3b-c405e2502434.mp4

but yes to allow this per option is a good idea. Do you mean exactly this to open a file by drag drop it to the app shortcut?
I am asking, because there is also possiblity to implement the original windows toolbar drag drop to move a file above or below the other, or to move a file out of windows toolbar by drag drop (but for user not always clear, if same drive it is a move, if other drive it is a copy). We tought these functions are confusing.

and there are more drag drop function possible and also we implemented a drag drop function that you can generate url shortcut and its icon by drag drop a url from a browser e.g. chrome into a submenu (before you need to pin the menu that it not closes due to focus lost) => probably too complicated to user

so best would probably be to open a fresh new issue https://github.com/Hofknecht/SystemTrayMenu/issues
and describe which drag drop exactly, if you mean exactly this like in the video and the title is fine of this one, we can also reopen this issue.

Thank you for your support

**Comment by the-phuctran** [comment]
Yes, your video is exactly feature that I wish it to have, drag files in menu for reordering is fine but not neccessary, drag files outside the menu for opening them in other programs is extremely helpful e.g drag pdf files for sending to gmail.com in Chrome, e.g drag photos to Paint to import. Pining menu feature is a good ideas but as the user of Windows 10 toolbar I don't think I will use this much for drag files in as I already have the right-click menu for pasting files to submenu folders because it's too narrow to drop the file correctly, and I use drag&drop for sending/exporting the file from menu to other programs, but it will be nice if the menu can be pined as I don't have to redo the step open the menu to drag many files and folders over many times anymore.

**Comment by Hofknecht** [comment]
Bob said he wants it like this
https://user-images.githubusercontent.com/52528841/142757699-62ec845c-e119-4306-9fcc-8232cf79a01a.mp4

**Comment by Hofknecht** [comment]
ok is now working, version 1.1.0.5

@the-phuctran here a video how it looks like, is this also what you expected?
https://user-images.githubusercontent.com/52528841/143137348-1821daf4-bfe8-44f0-a544-eba7c56c8174.mp4

if any more idea's related to drag drop, let me know

**Comment by the-phuctran** [comment]
Yes it's perfect thank you for working hard on this 🥰
