### ISSUE TITLE
[BUG] Task View: STM window sometimes too large

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#358]
**Description, Steps to reproduce, Expected behavior, Screenshots**

When using Task View the STM window was always too large but mostly fixed in https://github.com/Hofknecht/SystemTrayMenu/issues/299.
After a computer restart or starting a new instance of STM the over large window is (sometimes) still shown.

![Screenshot 2022-02-16 091801](https://user-images.githubusercontent.com/48499740/154235635-f5b3ecb4-f6f2-4e24-b8d7-df94df7f88ef.png)

Toggling STM in the taskbar to lose and gain focus fixes it and it goes back to the correct small size.
![Screenshot 2022-02-16 093705](https://user-images.githubusercontent.com/48499740/154237736-b3811a73-d054-45bf-977e-95c16c7638eb.png)

 - Windows 11 Pro   22000.493  (latest stable)
 - SystemTrayMenu 1.2.7.0

**Comment by Hofknecht** [comment]
@chip33 
Thank you for reporting and thank you for looking so closely!

i tried with restart, but in my win 11 test enviroment it did not occur, stays always like this:

![2022-02-16 16_46_04-ADE-MCG03797 - ADE-MCG03797 - Remote Desktop Connection](https://user-images.githubusercontent.com/52528841/154301680-650df9e5-0996-4c01-b67e-52fc9fa50919.png)

as long as there is no error and it's only cosmetic and it resolves itself quickly I can live with it : )

**Comment by chip33** [comment]
Yes,  it only seems to occur at startup or new instance so it isn't too bad.
Closing and restarting STM is just as effective at getting it to go big and it is fixed by minimising it a few times. 
No need to restart to try to test if it happens for you.
If you just try Task View sometimes when starting STM maybe you will be able to reproduce it.
Maybe other people will be able to report it too.
I

**Comment by chip33** [comment]
Hi , please could you close this then so it doesn't stay in issues and maybe re open it if it comes up again?

**Comment by Hofknecht** [comment]
Yes that is a good idea,
In any case, we are very grateful that you informed us here again. We actually want perfection, maybe we'll come back to that later sometime. I will mark as FAQ, as kind of known issue
