### ISSUE TITLE
[Feature] Better colors handling

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#37]
issue1:
better colors for selected and hover ones and was too bright

issue2:
selected folder other color than hover (as hover still too bright?)

issue3:
no more yellow, is strange

issue4:
grey color when inactive

issue5:
RootFolder when not selected should not be in hover color, maybe also white
RootFolder when selected     should not be in selected color, maybe only hover

idea
when key used disable mouse enter
when mouse move enable mouse  enter
=> problem enable is too fast, we miss logic

we only get mouse move when on app
we cannot seperate between enter&move with and without mouse move
e.g. waiting for several move events or miss first enter event has problems e.g. first next selected item by mouse will be missed
can we wait short period to disable logic? probably no because then shortly wait on any item will cause the mouse again to enter and this will be strange again then?
we always not know how long the menu needs to open so always wrong idea in this way!
how can we differ 1. enter+mousemove 2. enter+mousemove (we only know keypressed before x ms?)

So if your program wants to detect whether the mouse has moved, 
you need to add a check in your WM_MOUSEMOVE that the mouse position is different 
from the position reported by the previous WM_MOUSEMOVE message.

**Comment by Hofknecht** [comment]
open: 
-seems slower (maybe because of get cursorposition => solve with bg thread? suggested like this in an article, consider to link it here), verify why and solve
-codebeauty (maybe ok? verify maybe codestyle at all in other issue)
-RootFolder still hover color, is ok or further changes?
-consider to put issue4: grey color when inactive as extra feature

**Comment by Hofknecht** [comment]
i think open is
issue4:
grey color when inactive

and read trough idea

**Comment by Tanjalibertatis** [comment]
we solved open inactive issue with #61
