### ISSUE TITLE
[Feature] Sort folder contents by date

### ISSUE THREAD

**Issue by dna5589** [Hofknecht/SystemTrayMenu#370]
First off, this is an unbelievable program. So useful for me, so thank you!

When I go into folders that are set up, all the files in there are listed in order by their name. It would be awesome to have the option (set in Settings?) to be able to sort by date and have the newest files at the top. When there's a few hundred files in a folder for all our drawings, it's nice to have the latest stuff at the top. I can still search for any name I need but I can't search for a date order.

Hope this is clear enough!

**Comment by Hofknecht** [comment]
@dna5589 
Thanks for the suggestion, I made a small change here. Would that work for you? Can you confirm that it works correctly?
![2022-03-29 10_54_07-Window](https://user-images.githubusercontent.com/52528841/160574241-d9dc6d8d-4e16-43c2-bb7f-0c183d474930.png)

**Comment by dna5589** [comment]
That looks great! I'm assuming newest goes at the top since there's no ascending/descending option with it.

I'm on the Microsoft Store version right now but could try a portable build to confirm. (I don't have too many permissions here at work to install things) Whatever is easiest for you

Thank you!
