### ISSUE TITLE
[BUG] Batchfiles are not executed from their storage directory

### ISSUE THREAD

**Issue by not-nef** [Hofknecht/SystemTrayMenu#372]
**Batchfiles are executed from the system tray menu executable directory and not from the path they are stored. Can you please fix that?**

 - OS: Windows 11
 - 22000.556

**Comment by Hofknecht** [comment]
@not-nef 
Thank you for the feedback!

It seems it was correct in 1.019.3
![2022-04-10 23_08_35-Window](https://user-images.githubusercontent.com/52528841/162640033-eb54fdfb-1bd5-4b33-b4f3-b39df9d0cd42.png)

but somehow i changed/removed working directory in 
![2022-04-10 23_08_49-Window](https://user-images.githubusercontent.com/52528841/162640044-4174b75f-45e2-41d1-8ae5-eec89a548ec0.png)

test script e.g.:
```
echo %~dp0
pause
```

results in:
![2022-04-10 23_12_12-Window](https://user-images.githubusercontent.com/52528841/162640073-edd60884-8cc5-4243-8551-f2c0d4eff0b8.png)
(as you described => NOK)

when adjusting the line to this
![2022-04-10 23_13_08-Window](https://user-images.githubusercontent.com/52528841/162640119-0d428590-2812-4505-be63-2c047c854355.png)

then it works correct:
![2022-04-10 23_14_03-Window](https://user-images.githubusercontent.com/52528841/162640141-6d9cb15b-6337-4497-9688-b8102878e7ed.png)

added it to my tests, so this should prevent that this happens again 

in my tests i had another testcase related to working directory but seems to be wrong:
```
@rem test.bat
@echo off
echo %*
echo working directory: %cd%
PAUSE
```


now changed with version 1.2.9.3
Can you agree that it is working with changes from this commit?

**Comment by not-nef** [comment]
Uhhhhhhhhhhm... Sorry but i got a bit overwhelmed. So you want me to compile stm and verify it works?

**Comment by Hofknecht** [comment]
@not-nef 
If you want to you can verify if it works correct in your test cases. Very good that you reported it, thanks for that.
It is now in testing and will be in the next release.
