### ISSUE TITLE
[BUG] High-DPI issue over Remote Desktop

### ISSUE THREAD

**Issue by donaldaken** [Hofknecht/SystemTrayMenu#378]
I've been using STM on my personal laptop for many months - and loving it. I decided to use STM on my work desktop. I use Remote Desktop to connect to the headless work desktop. But the **STM windows, fonts, and icons are tiny.** The screenshot shows STM menu and settings, with a background of Windows File Explorer and taskbar. Huge difference in font and icon sizes!

![SystemTrayMenuHighDpiIssue](https://user-images.githubusercontent.com/96361296/166482662-f7b150a3-d5fc-42bf-a08e-1c44e0834cef.png)

Does anyone else have this issue? 
Is there anything to be done on the STM sided? 
Is there anything I can configure on the remote computer?

I set "% size" to its maximum 200% in STM. That makes the menu look good enough. But the settings dialog and right-click properties menu are still tiny, and scrolling is too fast.

I installed STM from the Windows Store. But I originally installed STM using the .zip. Both showed the same issue. 

 - Local OS: Windows 10 Home 21H2
 - Remote OS: Microsoft Windows 10 Enterprise 1909
 - STM Version 1.2.9.0
 - Display resolution: 2256 x 1504
 - Display scale: 175%

**Comment by Tanjalibertatis** [comment]
@donaldaken
Thanks for reporting! We were able to reproduce a similar behaviour, when we change the scaling while the STM is running.
The scaling is only taken over after a restart of the STM. In our case (we think it should not be related to Remote Desktop), after a restart, the context menu and the settings menu are also the right size. Please try this solution and give us feedback if this worked for you.

When scrolling, we always skip 3 items (regardless of the size of the menu). I think we can make a setting for that. (In windows explorer it is 2 to 3)

**Comment by donaldaken** [comment]
@Tanjalibertatis 
Thanks for responding! Exiting and restarting STM does not fix the issue for me.

This is a real head-scratcher. I had issues like this years ago for old apps and not related to Remote Desktop, but haven't seen this in a while. I can't actually go to the computer anymore to see what happens without Remote Desktop. I searched the web but didn't find anything.

I will try the compatibility settings in file properties. But I'll need to uninstall the Windows app and install the zip because I don't know how to access file properties of these new-fangled Windows apps.

**Comment by donaldaken** [comment]
Success. I changed the compatibility settings in the file properties of SystemTrayMenu.exe. Tic "Override high DPI scaling behavior", and change "Scaling performed by" from "Application" to "System".

![image](https://user-images.githubusercontent.com/96361296/166851559-6bf2a41c-40e1-4dfb-b6b6-deed10e2a9e3.png)

It's still a mystery why I need to do this.
