### ISSUE TITLE
[Feature] Installer & Updates

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#4]
We should create an update process 
Do we need an installer therefore? There is an installer and updater in when using the visual studio publish

Setup and update process should be like e.g. Notepad++
At least we need a function, check for updates now

**Comment by Hofknecht** [comment]
linked in [Archieve] #50

**Comment by Hofknecht** [comment]
ideas 

from logitech
![image](https://user-images.githubusercontent.com/52528841/78513952-32979b00-77af-11ea-9aa5-9c1c0e8d5514.png)
from notepad
![image](https://user-images.githubusercontent.com/52528841/78513964-404d2080-77af-11ea-9511-5229fc8093a3.png)

**Comment by topeterk** [comment]
It could be polished, but I like the idea of using the GitHub release notes to dump all the patch notes from the current version up to the latest one as I did this [here](https://github.com/topeterk/HitCounterManager/commit/f6eed29252cc8834e75da9daa536ead351a9b4de#diff-359b4f3eb4464476248037bc27b14ea6). This way the user can see what was done and I don't have to host or pre-define patch notes for the update process.

An example of the current implementation:
![image](https://user-images.githubusercontent.com/4932525/83926486-37b29f80-a78a-11ea-8065-e3d0c29f8913.png)

**Comment by Hofknecht** [comment]
yes the hint to inform user is good

i can also imagine such a form
![image](https://user-images.githubusercontent.com/52528841/88885171-47a1a980-d238-11ea-87a9-e8e56498b3da.png)

in this screenshot as example the tool netscan. When starting the tool user has to press download which opens the download page with release notes before app starts

planned with version 1.1

**Comment by topeterk** [comment]
Please keep in mind, not to force an user to do an update and moreover don't force him to do it right now!
A good example for automatic updates is, having the user options for "do not ask me again", "remind me later" and "update now".

Btw: Are the special requirements for updates of version that are installed via Windows Store?

**Comment by Hofknecht** [comment]
we tought about this:
checking for version will have impact on startup time => bad
showing a dialog will disturb the user => bad

Updates posible over Microsoft Store app silently in background

We would need to detect if we are the portable version or the microsoft app
Basically possible to implement in portable version the mentioned tihngs above

We hope for now it is enough that when there is a problem in the portable version the user can press right click 'Help / FAQ' and check if there is a new version by himself

=> won't fix/change for now
