### ISSUE TITLE
[Bug] Fix scrollbar visibilty due to resize options menu #406

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#407]
On my 4K (350% display scaling) monitor since v.1.2.9.28  [#406](https://github.com/Hofknecht/SystemTrayMenu/commit/75b06489839cb6744b9610a3ed537218b0677153) the Optionsmenu allways opens with  scroll bars at top and bottom although it does fit the whole menu on screen.

If I manually resize it to show the full Optionsmenu that resize is not remembered and every time I open the Optionsmenu it needs to be manually resized again.

Could the Optionsmenu remember the manually resized settings to prevent this happening?

Or is it possible to better detect the resolution and display scale level at which DTM decides it needs to show the scroll bars?

![Screenshot 2022-07-09 130017](https://user-images.githubusercontent.com/48499740/178105260-b2e145ef-91ad-477a-9cf6-cc73d8623321.png)

![Screenshot 2022-07-09 173225](https://user-images.githubusercontent.com/48499740/178114685-57f1464e-8476-44c1-b070-c31fb9aeb7e9.png)

**Comment by Hofknecht** [comment]
@chip33 Thank you for your fast feedback
comitted a first draft only for first tabpage in #406
it should appear without scrollbars, I will revise that again

**Comment by chip33** [comment]
> @chip33 Thank you for your fast feedback comitted a first draft only for first tabpage in #406 it should appear without scrollbars, I will revise that again

Thanks, I just slightly edited my first post above

**Comment by Hofknecht** [comment]
@chip33 
renamed the title
added this to your thx section in readme and about : )
fixed with 1.2.9.29
now the form autosize as before and then switches into resize mode afterwards, so that it is always ensured that scrollbars not more visible default only when resize

**Comment by chip33** [comment]
Thanks, smiles , we are fast today. Just checked new compiled version and it works nicely.
