### ISSUE TITLE
[BUG] Exceptions when fast open close stm

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#41]
see comments below

**Comment by Hofknecht** [comment]
-close long term issues, link to one new feature task e.g. like 'archive - ideas from closed issues'

**Comment by Tanjalibertatis** [comment]
we think that is fixed now, has to be tested

**Comment by Tanjalibertatis** [comment]
we think that is fixed now, has to be tested for longer period

**Comment by Tanjalibertatis** [comment]
TODO: Win32Exception when fast open close stm, does this still exist (#10)

**Comment by Hofknecht** [comment]
now fixed with 0.9.2.23
