### ISSUE TITLE
[Feature] Add English GB language support

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#414]
Here is an English GB language resource file for adding to STM.

Only "Customize" and several uses of "Color" needed changing for en-GB.

[lang.en-GB.resx.txt](https://github.com/Hofknecht/SystemTrayMenu/files/9120084/lang.en-GB.resx.txt)

It was previously discussed [here](https://github.com/Hofknecht/SystemTrayMenu/discussions/402) where some possible modifications to the English language strings in STM are also discussed.

**Comment by Hofknecht** [comment]
@chip33 
Thank you for the feedback!
Now en-GB available and also your suggestions from #402 included

**Comment by chip33** [comment]
Thank you, works very well. :)
