### ISSUE TITLE
[Feature] Settings menu - Always on top behavior

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#417]
### Discussed in https://github.com/Hofknecht/SystemTrayMenu/discussions/416

<div type='discussions-op-text'>

<sup>Originally posted by **chip33** July 17, 2022</sup>
I noticed that the Settings menu is set to Always on top which means you have to mouse click the minimize button to hide it.
Would it be better if it was not Always on top? 
I checked with some other applications to see what is the more usual behaviour and their Settings menus are not generally set to Always on top.</div>

**Comment by chip33** [comment]
Tested, working, does seem much better this way. Thanks :)
