### ISSUE TITLE
[Feature] Default "Icon size" and "Row height" to match Windows File Explorer

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#418]
It would be neat if the default (100%) values of "Icon size" and "Row height" in Settings -> Size and location matched those of Windows File Explorer.

If the default settings for Application size, Icon size and Row height were then all set to 100% a new STM install would automatically produce an interface that perfectly matches the Windows UI settings at all display resolutions.

On my 4K display I have set "Application size" to 100% and "Icon size" to 74% and "Row height" to 124% to match Explorer and tested this with varying resolution and display scaling values.

Optimal 4K settings:

![Screenshot 2022-07-19 153002](https://user-images.githubusercontent.com/48499740/179779202-5ac4e4f5-17a9-4a7b-97b8-8869747045f0.png)

At 1080 resolution, (changing display scaling doesn't seem to alter the results), "Icon size" at 90% and "Row height" at 116% gives the most exact equivalence to Explorers spacing values.

The "Icon size" of 90% @ 1080 does not tally with 74% @ 4K so could the default value be refactored to be the same as the Windows File Explorer icon padding? 
This way the default would match with the icon size in Explorer across all resolutions.

Default "Row height" could also be coded to be 'resolution independent' so that it also matches Explorer at all resolutions.

Optimal 1080 settings:

<img width="607" alt="1080" src="https://user-images.githubusercontent.com/48499740/179742654-cb211031-98ca-42f4-ae7e-77731cefff68.png">

4K settings (74% and 124%) on 1080 display:

![Screenshot 2022-07-19 125800](https://user-images.githubusercontent.com/48499740/179746658-40893127-07b0-40fd-8a06-5ec00a55b70a.png)

**Comment by Hofknecht** [comment]
@chip33 
Thank you for the hint!
I had to fight a bit here, now seems to work fine, at least much more precisely.

The cause of the wrong height was the automatic adjustment of the data grid view. It differs depending on dpi size. Own calculation of height seems be be accurate.

the size of the icon was in relation to the height, which i have now removed. I also added a calculation so it is now very similar to windows explorer. (you may have to increase the row height if you want to enlarge the icon)

I also improved the horizontal spacing to the text.

it also now works correctly with option application size in percent.

I also improved the logic of whether a small or large icon is used, so that it now looks sharper.

Default is now application size from 125% -> 100%


it is now adapted to windows explorer from windows 10. I hope that it is similar for you under Windows 11 or I think the row height is a bit larger, but that should now be a stable value for all resolutions.

We would be happy if you look at it again to see if it fits now and if you notice other things

**Comment by chip33** [comment]
Hi , amazing! I absolutely will check it out. Windows 11 has a wider default row height than windows 10 but I have set the option back to match Windows 10 by selecting "Compact View" in File Explorer.
I will check this out with the wider Windows 11 height setting too.

![Screenshot 2022-07-27 210143](https://user-images.githubusercontent.com/48499740/181361867-07d222f5-6b0f-4f29-a70a-18c5b1d4fdfe.png)


Thanks for doing this :)

**Comment by chip33** [comment]
Hi, I have been looking at this great change. 

Screenshots are all at 4K but I also tested Row heights at 1080 and results are all exactly the same and resolution independent!

Plus, I am on Windows 11 Insider Beta build 22H2 so these changes appear solid on the next release of Windows 11.

1. bug in auto refresh root folder where a blank space is left when an item is deleted. If STM is then closed and reopened the space disappears.
![bug on remove items refresh](https://user-images.githubusercontent.com/48499740/181886877-cc0684d9-fe37-4712-995c-43dc8c958f76.png)

2. Row height ( & icon size) at 100% is absolutely perfect with windows 11 compact view.
3.  Row height ( & icon size) at 156% is absolutely perfect with windows 11 default view.
![row height 156_](https://user-images.githubusercontent.com/48499740/181895088-40f9518d-6d39-4be9-9c1f-848a5cc59402.png)

So I superimposed screenshots of File Explorer to see what the actual new Windows 11 default Row heights is... It is NOT 150% your value of 156% is very close. Amazing.
Row height 150% test:
![Test row height 150](https://user-images.githubusercontent.com/48499740/181903462-9153b2f1-417d-41c7-bc17-f585af4df72e.png)

Row height 156% test:
![Test row height 156](https://user-images.githubusercontent.com/48499740/181903192-ce957dda-5527-4eb8-aea8-a828abd1fffd.png)


4. I did notice that since this change and not with 1.3.0.6 that clicking the OK button on the Settings menu (even when no changes are made) causes the Settings menu to lag and remain open for 4 seconds before closing.

**Comment by chip33** [comment]
I did notice that since this change (and not with 1.3.0.6) clicking the OK button on the Settings menu (even when no changes are made) always causes the Settings menu to lag and remain open for 4 seconds before closing. 
![Settings_lag](https://user-images.githubusercontent.com/48499740/181906039-b01a2ca6-e03e-4582-92e8-9ef0a39e2240.gif)

**Comment by chip33** [comment]
If you change the windows resolution while STM GUI and or the Settings menu are open the STM GUI and the settings menu do not resize correctly until you restart STM.
I don't know how easy it is to trigger a STM restart on display resolution change but that would stop this issue.

**Comment by Hofknecht** [comment]
@chip33 
Thank you for the feedback! i understand it is working fine.
point 1. fixed here: #430
topic related to slow option: fixed it here in last commit version 1.3.0.13

the topic related to change dpi required restart of app. There is an event dpichanged, but I detected that the event was triggering too often, e.g. when starting a game, so i removed it. i will check again if we can use this event without triggering too often. i made a note in project

If I've missed something, please write again : )

**Comment by Hofknecht** [comment]
@chip33 
related to live dpi adjustment raised by you https://github.com/Hofknecht/SystemTrayMenu/issues/418#issuecomment-1200501974)
find my answer here #437 
=> unfortunately without a solution for now but we have described the problem and maybe we will come up with something in the future
