### ISSUE TITLE
Pin to Windows 11 taskbar

### ISSUE THREAD

**Issue by halabiroger** [Hofknecht/SystemTrayMenu#424]
Hello,

I am using SystemTrayMenu with Windows 11, but don't see an option to pin to the taskbar, is this available or can it be added as a feature in a future version?

**Comment by halabiroger** [comment]
Sorry I found the setting, thx.

**Comment by Hofknecht** [comment]
@halabiroger 
Thank you for the feedback!
it's good to know that the feature is being used!
![2022-07-25 08_24_21-Window](https://user-images.githubusercontent.com/52528841/180711783-c69cb276-87f1-47c1-9def-5b2d7d1fbe5d.png)
