### ISSUE TITLE
[Feature] Make "draggable" zones for when Title bar is hidden

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#428]
If the "Show directory title at top" checkbox is disabled there is no visible area on the STM GUI to drag it with.
Could the blank space where the Function keys are located also be a "draggable" area?
It would be convenient to be able to drag it both from the top or the bottom.

![Screenshot 2022-07-28 141623](https://user-images.githubusercontent.com/48499740/181521674-fa1b73c2-1d6d-407e-a2e3-f13725de41a4.png)

Edit:
I just realised there is a small amount of space at the top of STM when there is no Title bar where it can be dragged but it is very hard to find and select so maybe the draggable area at the top could be made slightly bigger if needed and highlighted but only on a mouseover?

This would work even if the Title bar and Function key bar are hidden.

![Screenshot 2022-07-28 161756](https://user-images.githubusercontent.com/48499740/181585400-36500122-f23e-4497-a828-f414fb71072e.png)

**Comment by Hofknecht** [comment]
@chip33 
Thank you for the feedback!
we agree with you because since we don't show the title bar by default the drag manu should be more readily available. We added the lower function bar and the table layout from the menu to dragable zones. Now it should be easier to move the menu.
