### ISSUE TITLE
[Feature] Better behaviour of double click on notify icon

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#43]
Sometimes nothing happens after double clicking on the notify icon => document when, and also why

Further idea: Maybe a double click should open the root folder (not sure, think about that)

**Comment by Hofknecht** [comment]
open folder on double click menu
maybe we can add to right click 'open folder'

comes to archived ideas

**Comment by Tanjalibertatis** [comment]
besides that we had problems with very fast open closes of the STM, but now those are probably fixed

**Comment by Hofknecht** [comment]
solved with #10, i think double click to open defined folder is wrong => closed
