### ISSUE TITLE
[BUG] 'Show directory title' incorrectly displayed when in 'relative directory' mode

### ISSUE THREAD

**Issue by boydfields** [Hofknecht/SystemTrayMenu#435]
When 'Relative directory' is set and 'Show directory title' is enabled, the title displayed is "dot dot". It should enumerate the current directory and display the name.

![SystemTrayMenu_GD7rFi2YdC](https://user-images.githubusercontent.com/46451679/182831509-dd96da4b-bf3a-411a-9465-88aaeec31a5d.png)

 - OS: Windows 10 Enterprise
 - Version 19044.1766
 - App version: 1.3.0.0

**Comment by Hofknecht** [comment]
@boydfields 
Thank you for the feedback!
We will have a look.

**Comment by Hofknecht** [comment]
@boydfields 
now fixed with 1.3.0.16
we mentioned both tasks in thx section in about and readme : )
We hope you will find more!
