### ISSUE TITLE
[Feature] Increase performance of huge folders by iconcache

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#44]
https://www.howtogeek.com/howto/12383/change-a-file-types-icon-in-windows-7/

only one icon possible per filetype
except: exe, ico, ink, url (expecially game url)

... are there more?

**Comment by Hofknecht** [comment]
still open: exception happened (dicctionary not threadsave), log needed

**Comment by Hofknecht** [comment]
Commits on Mar 15, 2020
0bdbfa3
#NewFeature1 Increase performance by iconcache

**Comment by Tanjalibertatis** [comment]
solved
