### ISSUE TITLE
[BUG] Search bar in sub directory for empty directories

### ISSUE THREAD

**Issue by chip33** [Hofknecht/SystemTrayMenu#443]
This was introduced in [commit 123bece7](https://github.com/Hofknecht/SystemTrayMenu/commit/123bece791cc2fa0f7d70c5e7c31d3421e7b3d1b).
Even when "Show search bar" is unticked an empty folder shows a non working search icon.
![Screenshot 2022-08-10 172311](https://user-images.githubusercontent.com/48499740/183962439-988bdf34-9ab0-430e-abb7-913b542edb61.png)

STM v 1.3.1.0

**Comment by Hofknecht** [comment]
@chip33 
Thank you and sorry for late reply!
Now fixed version 1.3.1.1

**Comment by chip33** [comment]
Smiles. No worries . Im on holiday anyway :)
