### ISSUE TITLE
[BUG] Language Italian and Irish

### ISSUE THREAD

**Issue by timinformatica** [Hofknecht/SystemTrayMenu#446]
Version 1.3.1.0
In the languange settings I don't see "Italian", but if I choose "Gaeilge" it is Italian...

![immagine](https://user-images.githubusercontent.com/32060141/187377394-da81f99c-3fd7-48c2-916d-254d175984a6.png)

**Comment by Hofknecht** [comment]
@timinformatica 
Thank you very much for your feedback!
There was a copy error, now it should work with version 1.3.1.3

we added you in the thx section in readme and about menu
