### ISSUE TITLE
[Feature] Sort method for grouping by file extensions

### ISSUE THREAD

**Issue by ppt-oldoerp** [Hofknecht/SystemTrayMenu#450]
Happy with this tool with one exception: sort order.
In options I set sort order to "Type and Name". I expected type is the windows file extension. I expected all with same extension and inside of them by name. Ongoing for each extension.

I options I also added a folder with xxx.rdp files inside

Sort result seems to ignore type and all are sorted by name:

Windows 11 21H2 build 22000.978
![Folder_option](https://user-images.githubusercontent.com/65767666/191956195-c855809e-662f-490e-93c4-2e8da8ffc053.png)
![result_list](https://user-images.githubusercontent.com/65767666/191956198-e5705bed-f8a7-4449-9e84-368087185434.png)
Files without extension in list are links (Icon on desktop)

Wolfram

**Comment by topeterk** [comment]
I checked the code and it looks to me as I remembered it:  
``` csharp
            if (Properties.Settings.Default.SortByTypeAndNameWindowsExplorerSort)
            {
                rowDatas = rowDatas.OrderByDescending(x => x.IsFolder)
                    .ThenBy(x => x.Text, new WindowsExplorerSort()).ToList();
            }
            else if (Properties.Settings.Default.SortByTypeAndDate)
            {
                rowDatas = rowDatas.OrderByDescending(x => x.IsFolder)
                    .ThenByDescending(x => x.FileInfo.LastWriteTime).ToList();
            }
            else if (Properties.Settings.Default.SortByName)
            {
                rowDatas = rowDatas.OrderBy(x => x.Text).ToList();
            }
            else if (Properties.Settings.Default.SortByDate)
            {
                rowDatas = rowDatas.OrderByDescending(x => x.FileInfo.LastWriteTime).ToList();
            }
```

Type is meant to be "folder or file", so the folders are first and then the files are listed. Then each of the two groups are sorted by their names like it is done by WindowsExplorer.

As of today this is by design.

However, it should be not a big deal to add a "grouping" for file extensions as well. I'll turn it into a feature request.

**Comment by ppt-oldoerp** [comment]
Hi topeterk,

thank you for explain "type" and changing from Bug to Request.
My proposal is in the captions of options to change from "Type" to "Folder" to make it more clear.
Wolfram

**Comment by Hofknecht** [comment]
@ppt-oldoerp 
Thank you for the feedback!
we adjusted the text:
![2022-10-05 21_55_58-Window](https://user-images.githubusercontent.com/52528841/194151102-9e141718-5abc-489f-84e1-89841539eaaa.png)

we added you to the Thanks section in readme and about!

We look forward to hearing more from you, please give us further feedback : )

i will close, if something missing, you can reopen or create new one any time

**Comment by topeterk** [comment]
@Hofknecht This issue was not about just a "wrong text" or any "bug". It is about sorting by the files' extension and this updated text does not solve the requested "feature".
Sure, you actually want to close this?
(This implicitly means, a sorting mechanism by file extension will not be implemented)

**Comment by Hofknecht** [comment]
@topeterk 
Thanks for the hint, I wasn't quite sure if it was needed.
i added sort by file extension and then by name
see also here in screenshot:
![2022-10-06 18_51_21-Window](https://user-images.githubusercontent.com/52528841/194372597-b78b0828-a4d0-43cd-a0dd-84b284a58a58.png)
version 1.3.1.6

@ppt-oldoerp
does that meet your requirements? do you need more? we look forward to further suggestions

**Comment by ppt-oldoerp** [comment]
sorry, may be, I have tomato on my eyes - how / whre can I download the 1.3.1.6?
Inbuilt update function says 1.3.1.0 would be latest.
Thank you

**Comment by Tanjalibertatis** [comment]
> sorry, may be, I have tomato on my eyes - how / whre can I download the 1.3.1.6? Inbuilt update function says 1.3.1.0 would be latest. Thank you

@[ppt-oldoerp](https://github.com/ppt-oldoerp)
That's right, 1.3.1.0 is the latest release version. The feature will be in the next release version (1.3.2.0), not sure when exactly that will be out. To test it earlier, you can download the code and build your own version in Visual Studio.
