### ISSUE TITLE
[Feature] Prevent open Folder-Links (LNK Files of a Folder) as Directory in STM

### ISSUE THREAD

**Issue by fubaWoW** [Hofknecht/SystemTrayMenu#453]
**Is your feature request related to a problem? Please describe.**
Any chance to "prevent" open Folder-Links (*.LNK Files of a Folder) as "Directory" in [SystemTrayMenu](https://github.com/Hofknecht/SystemTrayMenu)?

**Describe the solution you'd like**
Add a function to just open **REAL** Subfolders in selected "Directory" but NOT open Folder-Links (*.LNK-Files of Folders) as a Directory in [SystemTrayMenu](https://github.com/Hofknecht/SystemTrayMenu)

**Additional context**
For example:  
I got a Link of my "Recycle Bin" in the Root Folder of the "Directory"
I do not need to see any contents on "mouseover" for this folder (because it is just a Link, not a Real Folder!).
But i like to be able to Open it with a Single/Double Click (depends on Settings) AND also be able to Right-Click to Empty the Recycle Bin fast or for example.

This is actually working very well but in case i do not need to see the Contents of ANY Folder-Link the unnecessary "Loading-Times" of these Folders is not needed for me.

Would be very nice!
greetings

**Comment by Hofknecht** [comment]
@fubaWoW 
Thank you for the feedback!

Sounds good, added a new option here

![2022-10-05 20_57_43-Window](https://user-images.githubusercontent.com/52528841/194140537-2a092fde-46dd-4c31-a0e8-f43b0c317582.png)

which is default true, you can disable it then links to folders will no longer be presented as extra menu

does that meet your requirements?

**Comment by fubaWoW** [comment]
yeah, looks very nice!

**Comment by Hofknecht** [comment]
@fubaWoW 
Thank you!
Then we will close the issue.

we added you to the Thanks section in readme and about!

We look forward to hearing more from you, please give us further feedback : )

**Comment by fubaWoW** [comment]
No -> Thank YOU!
happy to look forward for next Version ;)
