### ISSUE TITLE
[BUG] Languages Filipino, Hebrew and Norwegian not working

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#467]
Barack reported via mail that language 'Hebrew' not working

> 
> 
> שלום
> 
> בכל פעם שאני מכבה את המחשב, צריך להגדיר מחדש את התיקיה שהתוכנה תפעיל, האם ניתן להגדיר שזה יפעל בקביעות?
> 
> ניסיתי דרך האפשרויות ולא הצלחתי.
> 
> כמו כן ראיתי באפשרויות שפה שיש 'עברית' ולא הצלחתי להגדיר
> 
> אשמח לעזרתכם
> 
> תודה ברק
> 
> 

we answered

Hello Barack,
thanks for pointing out that hebrew is not functional. We'll fix that.
Do you think that the STM should start automatically when Windows starts (= autostart)? You can activate the autostart by ticking the language selection in English here:
![2023-03-01 22_06_57-Window](https://user-images.githubusercontent.com/52528841/222266471-6d66e464-4f02-4814-8e9d-f59b07a6dfed.png)

Let us know if that solved your problem.

**Comment by Tanjalibertatis** [comment]
also not working:
