### ISSUE TITLE
[Feature] Bugsplat, ask user to send error logfile

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#47]
When application crashed we ask user to send error as email

**Comment by Hofknecht** [comment]
Commits on Mar 15, 2020
0bdbfa3519c683017052e1111a2efd2cb94ab948
#NewFeature2 Ask user to send exception by standard mail and restart

**Comment by Hofknecht** [comment]
#warning [Feature] When Error ask user to send us #47, todo own dialog, lines here too long

e.g. see dialog from tortoise 
![image](https://user-images.githubusercontent.com/52528841/76762237-2fe9ed00-6791-11ea-9968-162c920aa415.png)

**Comment by Tanjalibertatis** [comment]
TODO
-implement own dialog
-is the mail not complete
-are all errors now in logfile, review code

**Comment by Hofknecht** [comment]
maybe we could make it like here?

![2020-08-01 08_27_00-Petroglyph Crash Report](https://user-images.githubusercontent.com/52528841/89121800-703cd400-d4c2-11ea-94f3-c0a9922b9f63.png)

**Comment by Hofknecht** [comment]
The basic problem on solutions to send us a report automatically is that we are a open source code and then we need to write the credentials into the code. That could be abused.

So i think for now to ask user sending us a mail is also good decision, because we also got some feedback and could inform the persons that the bugs were fixed

can stay as it is for now
