### ISSUE TITLE
[BUG] ArgumentOutOfRangeException at KeyboardInput.SelectPreviousMenu

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#477]
Thomas reported:

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')   at System.Collections.ArrayList.get_Item(Int32 index)   at System.Windows.Forms.DataGridViewSelectedRowCollection.get_Item(Int32 index)   at SystemTrayMenu.Handler.KeyboardInput.SelectPreviousMenu(Int32 iRowBefore, Menu

**Comment by topeterk** [comment]
https://github.com/Hofknecht/SystemTrayMenu/commit/1f985c53aac8076e807df67778f435201c2bb115#diff-b164a71d3b9b5026c543a6d953e7f704c7b2901a561caaf2940df1fbe8e275fdR490
Maybe this fix from version 2 might protect against this exception?
