### ISSUE TITLE
[BUG] Child processes won't elevate

### ISSUE THREAD

**Issue by DailenG** [Hofknecht/SystemTrayMenu#488]
### Discussed in https://github.com/Hofknecht/SystemTrayMenu/discussions/487

<div type='discussions-op-text'>

<sup>Originally posted by **DailenG** June 16, 2023</sup>
I'm running System Tray Menu on a user with no admin privileges and using shortcuts that launch chocolatey to install an application. I have SystemTrayMenu running with elevated privileges, I have chocolatey set to always run with admin privileges, but if I launch a shortcut from System Tray Menu it launches without elevation or prompting for elevation (either is ok). If I launch the shortcut directly it will prompt for elevation.

Am I doing something wrong or is there a workaround? I'm not sure how to get it to prompt aside from using a third party like gsudo to induce elevation.</div>

**Comment by Hofknecht** [comment]
@DailenG 
Thank you for the feedback!

i need to test with user without admin rights 

Normally UAC should work like here with Admin user:
![1](https://github.com/Hofknecht/SystemTrayMenu/assets/52528841/a77408d1-4ed1-40fd-b575-0334d61f6dcc)
![2](https://github.com/Hofknecht/SystemTrayMenu/assets/52528841/917db583-5eca-4940-b552-27bf19d85fe5)

**Comment by Hofknecht** [comment]
@DailenG 

ok now with normal user i can reproduce.
found this: https://stackoverflow.com/questions/16926232/run-process-as-administrator-from-a-non-admin-application
and with the change 
Verb = "runas",
it works

**Comment by Hofknecht** [comment]
@DailenG  will be in the next version (but i assume this takes a while), we added you to the thanks section : )

**Comment by Hofknecht** [comment]
when admin privliges then process does not start when using verb "runas"
checks for Admin not working so still open topic
we need to revert current change

**Comment by Hofknecht** [comment]
@topeterk  
The first solution was bad.
Now there is a new one [1.3.2.6], hope this works fine.
