### ISSUE TITLE
[BUG] Win11 only, Menu not opens via taskbar click when closed via taskbar click before

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#496]
When menu closed via taskbar icon click, then it is not possible to open the menu via taskbar icon click again, only when you e.g. click into the desktop or any other application.

Only win 11 issue.

Normally in win 10 the behavior is that you can open menu also in this case

Known bug, we will not fix for now
maybe the behavior can be improved later in v2

**Comment by Hofknecht** [comment]
won't fix for now, only for FYI and FAQ

**Comment by topeterk** [comment]
v2 "workaround": fb18265395a1d0f11b8517d1e24d2aa8060d6907
