### ISSUE TITLE
 [BUG] In v1.3.3 introduced a issue that always asking for admin, but should only ask if shortcut requires run as admin

### ISSUE THREAD

**Issue by spitzlbergerj** [Hofknecht/SystemTrayMenu#499]
I have just updated to the current version. I use the portable version. I downloaded it from github and unpacked it. When I now start the new version, everything is present as in the old version. However, when I start an application, I am now always asked for the admin password. My normal user has no admin rights.

If I start the old version, which is located in the directory "next to", the admin query does not come.

 - OS: Windows 11 
 - Version 22H2

**Comment by Hofknecht** [comment]
related
#488

**Comment by Hofknecht** [comment]
@spitzlbergerj 
Thank you for the feedback! Thank you for the donation!
added you to the thx and sponsor section!

we fixed the issue, now only for shortcuts where 'run as admin' is set the verb 'runas' is set instead to set it always when no admin. 
Uploaded to windows store yesterday, 
we can press release for 1.3.4 tomorrow

**Comment by JeckPeppinger** [comment]
Thanks for fixing, however, a fixed version is neither available here on GitHub nor on the MS Store.

Feedback for MS Store - I cannot see any version info there, checked all corners of the MS Store, maybe a version info exists somewhere, but this is not visible to me.

**Comment by JeckPeppinger** [comment]
@Hofknecht - are you sure a fix was published? A week now since you mentioned it is fixed and will be published "tomorrow". Confusing .... pls. clarify.

**Comment by Hofknecht** [comment]
now tried again and just submittted Packaging_1.3.5.0_x86_x64_ReleasePackage.msixbundle, needs some days

**Comment by Hofknecht** [comment]
now released in github 1.3.5

**Comment by JeckPeppinger** [comment]
Thanks, excellent, and it works like a charm again! Thx!
