### ISSUE TITLE
[Bug] Clipboard filled

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#5]
Clipboard is filled when doubleclicking on root folder
Open the STM and doubleclick on the root folder over the label at the top. Afterwards the name of the root folder is copied to clipboard.

**Comment by topeterk** [comment]
[Known bug/feature](https://stackoverflow.com/questions/17048395/double-clicking-net-label-control-copies-its-text-to-clipboard-on-vista) .. idk
Hmm either override the whole doubleclick handler from the Label class or save&restore clipboard befor/after calling the base class handlers.

**Comment by Hofknecht** [comment]
Great job! Thx for your help here!
