### ISSUE TITLE
[Feature] Filewatcher to update deleted files

### ISSUE THREAD

**Issue by Tanjalibertatis** [Hofknecht/SystemTrayMenu#51]
When you delete a file by right click in the STM, an immediate update would be nice.

**Comment by Hofknecht** [comment]
TODO: Find solution, be aware of any leaks or slow downs by e.g. filewatcher

**Comment by Hofknecht** [comment]
i normally just refresh the folder by leaving it and open it again, so i think that is not really a issue
=> will close this

**Comment by Hofknecht** [comment]
finally with #330 we implemented that feature
