### ISSUE TITLE
[Feature] Create FAQ

### ISSUE THREAD

**Issue by Tanjalibertatis** [Hofknecht/SystemTrayMenu#54]
What about a FAQ

**Comment by Hofknecht** [comment]
Consider to put the drag drop hint into FAQ

**Comment by Hofknecht** [comment]
maybe like this one 
https://getgreenshot.org/faq/

**Comment by Hofknecht** [comment]
todo:
when stm starts the first time we open the readme file and we put the FAQ for the first step into the readme file #67
