### ISSUE TITLE
[Feature] Create options menu

### ISSUE THREAD

**Issue by Tanjalibertatis** [Hofknecht/SystemTrayMenu#55]
Replace with an option dialog
![image](https://user-images.githubusercontent.com/52528841/78513298-d5014f80-77aa-11ea-8811-401cd881ef58.png)

e.g. like screenshot 
![image](https://user-images.githubusercontent.com/52528841/78513333-10038300-77ab-11ea-8ef7-ff18c3e026f5.png)

**Comment by Hofknecht** [comment]
TODO: should we make something configurable from the MenuDefines.cs e.g. time when STM closes when leaving by mouse and deactivated?

**Comment by Hofknecht** [comment]
![image](https://user-images.githubusercontent.com/52528841/80995419-8513b800-8e3e-11ea-98f3-96ab341d693a.png)
