### ISSUE TITLE
[Feature] Upgrade to UWP / .NET Core 3.1

### ISSUE THREAD

**Issue by Tanjalibertatis** [Hofknecht/SystemTrayMenu#57]
.NET Core is probably necessary in the future

as UWP app we can also get into windows store
https://docs.microsoft.com/en-us/microsoft-store/distribute-apps-from-your-private-store
https://developer.microsoft.com/en-us/store/register/
https://docs.microsoft.com/de-de/windows/uwp/publish/

for topic 'Using Windows Forms DataGridView in .NET Core 3.1' check https://gunnarpeipman.com/datagridview-dotnet-core-31/

Maybe we can keep .NetFramwork Solution to still see designer with DataGridView
https://docs.microsoft.com/en-us/dotnet/core/porting/project-structure

Fading
https://docs.microsoft.com/de-de/windows/uwp/design/motion/motion-fade

**Comment by Hofknecht** [comment]
https://github.com/dotnet/try-convert  executed

TODO
when changing to 
    <TargetFramework>netcoreapp3.1</TargetFramework>
these are the problems:
-ContextMenu in hotkeycontrol  (low)
-Microsoft.WindowsAPICodePack.Dialogs (middle)
-some informations from SetupInformation in AboutBox (low)
-settings designer configuration system failed to initialize (middle)

**Comment by Hofknecht** [comment]
TODO
* ![image](https://user-images.githubusercontent.com/52528841/83887924-69efdd00-a749-11ea-8aa1-5e5865fcf583.png)

**Comment by Hofknecht** [comment]
2 fixed, left ist:
* ContextMenu in hotkeycontrol (low)
* some informations from SetupInformation in AboutBox (low)
* settings designer configuration system failed to initialize (middle)

**Comment by Hofknecht** [comment]
3 fixed, seems now fully compatible in netcoreapp3.1

**Comment by Hofknecht** [comment]
it's running with targetframework .net core 3.1, 
but still not buildable with DotNetCoreCLI because of COMReferences in .NET Core 3.1 #91

rest seems closed

**Comment by Hofknecht** [comment]
Just for info
![image](https://user-images.githubusercontent.com/52528841/86507806-867c4500-bddb-11ea-8552-8592db94f60f.png)
This dialog should appear when starting the exe, but sometimes it did not appear and then i needed to update windows or install it manually
