### ISSUE TITLE
[Feature] NotifyIcon group outside into taskbar

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#58]
**The STM should be outside of taskbar**
![2020-04-06 02_14_44-](https://user-images.githubusercontent.com/52528841/78513522-9f5d6600-77ac-11ea-91d2-28d9668fec80.png)

**At the moment the user can/should do this manually.**

but e.g. dropbox can group it outside automatically (have in mind this is not conform)

FYI, removed code to show a hint form to user 
>                     // Idea is either to show always outside like dropbox 
>                     // (is nok due to windows rules, maybe only allowed when asking user?)
>                     // (or to give at least a hint that drag drop possible?)
>                     //bool IsNotifyIconInTaskbar()
>                     //{
>                     //    bool isNotifyIconInTaskbar = false;
>                     //    int height = screen.Bounds.Height -
>                     //        new Taskbar().Size.Height;
>                     //    if (Cursor.Position.Y >= height)
>                     //    {
>                     //        isNotifyIconInTaskbar = true;
>                     //    }
>                     //    return isNotifyIconInTaskbar;
>                     //}
>                     //if (!IsNotifyIconInTaskbar())
>                     //{
>                     //    //DragDropHintForm hintForm = new DragDropHintForm(
>                     //    //    Language.Translate("HintDragDropTitle"),
>                     //    //    Language.Translate("HintDragDropText"),
>                     //    //    Language.Translate("buttonOk"));
>                     //    //hintForm.Show();
>                     //}
& DragDropHintForm
from [Feature] DragDrop Hint #6

TODO: Ask google how dropbox does this and check in which way we can implement it

**Comment by Tanjalibertatis** [comment]
related to #6 DragDrop Hint

**Comment by Hofknecht** [comment]
![image](https://user-images.githubusercontent.com/52528841/80993487-6fe95a00-8e3b-11ea-8307-db58ab40a3c8.png)

at the moment this still needs to be done by user (see new win 10 picture, but easiest way for user is probably still by using drag drop)

TODO: Ask google how dropbox does this and check in which way we can implement it

**Comment by Hofknecht** [comment]
https://superuser.com/questions/318088/make-specific-tray-icon-always-show-for-all-profiles-in-windows-7
There is no way for applications to programmatically always show themselves top level on the system tray.

We will ask the user to do this when first time app was started together with other first start hints and FAQ in #67
