### ISSUE TITLE
[BUG] Autosizing columns and rows while scrolling

### ISSUE THREAD

**Issue by Tanjalibertatis** [Hofknecht/SystemTrayMenu#65]
improve Performance DataGridView Autosizing columns

**Comment by Tanjalibertatis** [comment]
there was a problem but now is fixed

**Comment by Hofknecht** [comment]
solved with #10

**Comment by Hofknecht** [comment]
![image](https://user-images.githubusercontent.com/52528841/78519137-aabb8c00-77c2-11ea-821c-f4638ac47d27.png)
is now fast but not more perfect

TODO: check improvements

**Comment by Hofknecht** [comment]
normally this isn't regocnized by user, we will close, because i find no better solution which is also same fast as this solution with this bug ; )
