### ISSUE TITLE
[Feature] Possible Memory or GDI Leaks, analyze and verify

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#68]
screenshots from taskmanager with version 0.9.2.16, highest values gdi & memory i could reach were:
![image](https://user-images.githubusercontent.com/52528841/78567616-3fed6d80-7821-11ea-9878-4aa780d596e4.png)
![image](https://user-images.githubusercontent.com/52528841/78567626-42e85e00-7821-11ea-887e-f3963ba8b07a.png)

e.g. issues with actions from keyinputhandler, therfore read again
https://stackoverflow.com/questions/1431359/event-action-vs-event-eventhandler
https://social.msdn.microsoft.com/Forums/en-US/9aaa17b7-ba44-4aea-8a30-28936d34d768/event-actionlttgt-vs-event-eventhandlerlttgt?forum=csharplanguage
TODO1: replace actions with events

Collect more info's here?
Memory GDI analyzer?

**Comment by Hofknecht** [comment]
analyze this also with this issue: i can imagine there is a problem when disposing takes long time, then loading is shown, but i can still click for a new main menu (working fine), but is then erverything disposed correct?

**Comment by Hofknecht** [comment]
good in official build 0.9.1.233
seems good again in version 0.9.2.22 (analyzed with Task Manager long term test fast open close comes back <30mb / comes back to <200 gdi objects
TODO: Test again when bigger changes made, check points from description

**Comment by topeterk** [comment]
AFAIK the GDI objects are removed from memory by calling DeleteObject which *should* be done by the framework itself and I doubt it having a memory leak. Therefore I guess this here is related to the Garbage Collector that you can clear on purpose manually as well? Have you considered that during your investigations? (This may also free up GDI objects that are owned by the managed objects (if that is a thing))

**Comment by Hofknecht** [comment]
> AFAIK the GDI objects are removed from memory by calling DeleteObject which _should_ be done by the framework itself and I doubt it having a memory leak. Therefore I guess this here is related to the Garbage Collector that you can clear on purpose manually as well? Have you considered that during your investigations? (This may also free up GDI objects that are owned by the managed objects (if that is a thing))

Thanks for comments and hints

It's possible to call GC.Collect() manually for testing purpose. Normally GC makes most things automatically. There are some few things to care about, e.g. calling dispose on timers or icons therefore most classes implement IDisposeble to not forget these things. Also wrapping by 'using' command is also good thing, to call this dispose automatically. Adionally .Net static code analysis and FixCop gave me hints for missing/not disposed objects. Special cases were also when thread fails, this should not more happen. Expecially in edge cases there were problems e.g. fast open closes #41

Tested again in latest version 0.9.2.23, seems good
I will close that issue
