### ISSUE TITLE
[Bug] Fix icon remains in systemtray

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#77]
Issue: Start STM 2x, then first notifyicon remains in systemtray (removes itself when mouse moves then  over it)
(Side Problem, Ressources could remain on the system? maybe related to #68)

Normally we set 'notifyIcon = null' to remove this icon when Dispose is called.
In this case application is restarted trough killProcess, see in code KillOtherInstancesOfApp();
so Dispose() not called  in this situation.

We are using this solution, because then restart always working, even when error happend in first instance and you are opening a second. (We can tell user instance is running and he can then kill the process manually, but this is annoying or?)

A solution we tried, was to tell first instance to close by file, this caused problems when using sync app's like seafile, dropbox etc. Maybe we can tell first instance to Dispose in an other way or is this not necessary because windows handles it obviously always correct?

**Comment by topeterk** [comment]
Not looked deeper into this yet, however I know from Win32 API you can create the NotifyIcon with a specific GUID. This way, when the application crashes or was killed, you can find the old zombie icon and continue using this.

**Comment by Hofknecht** [comment]
changed pre build event the /f forces, when you not put it there it closes gracefully
taskkill /fi "pid gt 0" /im SystemTrayMenu.exe
taskkill /f /fi "pid gt 0" /im SystemTrayMenu.exe

in code adjusted 

if (!p.CloseMainWindow())
                            {
                                p.Kill();
                            }
                            ....
                            p.Close();


solves the problem

**Comment by Hofknecht** [comment]
solution to clear systemtrayicon when application fails (but i think we not need it for now)

https://stackoverflow.com/questions/74723/can-you-send-a-signal-to-windows-explorer-to-make-it-refresh-the-systray-icons?rq=1

#define FW(x,y) FindWindowEx(x, NULL, y, L"")

void RefreshTaskbarNotificationArea()
{
    HWND hNotificationArea;
    RECT r;

    GetClientRect(
        hNotificationArea = FindWindowEx(
            FW(FW(FW(NULL, L"Shell_TrayWnd"), L"TrayNotifyWnd"), L"SysPager"),
            NULL,
            L"ToolbarWindow32",
            // L"Notification Area"), // Windows XP
            L"User Promoted Notification Area"), // Windows 7 and up
        &r);

    for (LONG x = 0; x < r.right; x += 5)
        for (LONG y = 0; y < r.bottom; y += 5)
            SendMessage(
                hNotificationArea,
                WM_MOUSEMOVE,
                0,
                (y << 16) + x);
}
