### ISSUE TITLE
[Bug] Screen Changes

### ISSUE THREAD

**Issue by Hofknecht** [Hofknecht/SystemTrayMenu#79]
When changing to an other screen (maybe it was special case through CEC to my beamer), it was once not working. 

Error was shortly shown, then it was restarted. => todo with #47
Should not restart before asking user to send logfile

And it was then even not in the logfile ....

(in this case the software restarts, so the user normally not regocnizes this, low prio)

TODO: Analyze Screen Changes and if this normally works, analyze the mentioned issue

**Comment by topeterk** [comment]
What kind of screen change are you referring to?
Resolution changes, active desktop changes, monitor unplugged, switched to e.g. clone mode....

**Comment by Hofknecht** [comment]
in my case it was like in this screen
![image](https://user-images.githubusercontent.com/52528841/83965641-52cdfe00-a8b5-11ea-95dd-3345f1d48f26.png)
 cloned mode(2&3) with addionals (4,1) and second cloned one (3) was turned on
but did not happen again, maybe meanwhile fixed or event did not came, not sure

nice list, tested addionally all of them, works fine
![image](https://user-images.githubusercontent.com/52528841/83965611-1dc1ab80-a8b5-11ea-8385-33d35a53a2eb.png)

also tried e.g. on mobile phone and tablet over rdp and switching horizontal vertical, works fine with scrollbar etc, so i can not find any issue

will close, no code changes

**Comment by Hofknecht** [comment]
![image](https://user-images.githubusercontent.com/52528841/84942853-c9ec6900-b0e3-11ea-8abe-3fe256504119.png)
when plugged out screen 1
